services:
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: ff_database
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "ffPass123!"
    ports:
      - 1433:1433
    volumes:
      - sqldata:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqldata: