using FantasyFootball.Models;

namespace FantasyFootball.Repositories
{
    public class PlayerMockRepository
    {
        private readonly List<Player> _players;

        public PlayerMockRepository()
        {
            _players = new List<Player>
            {
                // ==========================================
                // MANCHESTER CITY (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 1,  FirstName = "Erling",   LastName = "Haaland",     Position = Position.Forward,    Club = "Manchester City", Nationality = "Norway",      DateOfBirth = new DateTime(2000, 7, 21), MarketValue = 180.0, Goals = 27, Assists = 5,  CleanSheets = 0,  TotalPoints = 275 },
                new Player { Id = 13, FirstName = "Josko",    LastName = "Gvardiol",    Position = Position.Defender,   Club = "Manchester City", Nationality = "Croatia",     DateOfBirth = new DateTime(2002, 1, 23), MarketValue = 75.0,  Goals = 5,  Assists = 4,  CleanSheets = 12, TotalPoints = 160 },
                new Player { Id = 16, FirstName = "Ederson",  LastName = "Moraes",      Position = Position.Goalkeeper, Club = "Manchester City", Nationality = "Brazil",      DateOfBirth = new DateTime(1993, 8, 17), MarketValue = 35.0,  Goals = 0,  Assists = 1,  CleanSheets = 14, TotalPoints = 152 },
                new Player { Id = 17, FirstName = "Stefan",   LastName = "Ortega",      Position = Position.Goalkeeper, Club = "Manchester City", Nationality = "Germany",     DateOfBirth = new DateTime(1992, 11, 6), MarketValue = 12.0,  Goals = 0,  Assists = 0,  CleanSheets = 6,  TotalPoints = 68 },
                new Player { Id = 18, FirstName = "Ruben",    LastName = "Dias",        Position = Position.Defender,   Club = "Manchester City", Nationality = "Portugal",    DateOfBirth = new DateTime(1997, 5, 14), MarketValue = 70.0,  Goals = 2,  Assists = 1,  CleanSheets = 13, TotalPoints = 155 },
                new Player { Id = 19, FirstName = "John",     LastName = "Stones",      Position = Position.Defender,   Club = "Manchester City", Nationality = "England",     DateOfBirth = new DateTime(1994, 5, 28), MarketValue = 40.0,  Goals = 1,  Assists = 2,  CleanSheets = 11, TotalPoints = 128 },
                new Player { Id = 20, FirstName = "Kyle",     LastName = "Walker",      Position = Position.Defender,   Club = "Manchester City", Nationality = "England",     DateOfBirth = new DateTime(1990, 5, 28), MarketValue = 18.0,  Goals = 0,  Assists = 3,  CleanSheets = 10, TotalPoints = 112 },
                new Player { Id = 21, FirstName = "Manuel",   LastName = "Akanji",      Position = Position.Defender,   Club = "Manchester City", Nationality = "Switzerland", DateOfBirth = new DateTime(1995, 7, 19), MarketValue = 35.0,  Goals = 1,  Assists = 1,  CleanSheets = 12, TotalPoints = 135 },
                new Player { Id = 22, FirstName = "Kevin",    LastName = "De Bruyne",   Position = Position.Midfielder, Club = "Manchester City", Nationality = "Belgium",     DateOfBirth = new DateTime(1991, 6, 28), MarketValue = 55.0,  Goals = 6,  Assists = 14, CleanSheets = 0,  TotalPoints = 198 },
                new Player { Id = 23, FirstName = "Phil",     LastName = "Foden",       Position = Position.Midfielder, Club = "Manchester City", Nationality = "England",     DateOfBirth = new DateTime(2000, 5, 28), MarketValue = 110.0, Goals = 12, Assists = 9,  CleanSheets = 0,  TotalPoints = 205 },
                new Player { Id = 24, FirstName = "Bernardo", LastName = "Silva",       Position = Position.Midfielder, Club = "Manchester City", Nationality = "Portugal",    DateOfBirth = new DateTime(1994, 8, 10), MarketValue = 65.0,  Goals = 5,  Assists = 10, CleanSheets = 0,  TotalPoints = 168 },
                new Player { Id = 25, FirstName = "Mateo",    LastName = "Kovacic",     Position = Position.Midfielder, Club = "Manchester City", Nationality = "Croatia",     DateOfBirth = new DateTime(1994, 5, 6),  MarketValue = 30.0,  Goals = 3,  Assists = 5,  CleanSheets = 0,  TotalPoints = 118 },
                new Player { Id = 26, FirstName = "Savinho",  LastName = "Trovoada",    Position = Position.Midfielder, Club = "Manchester City", Nationality = "Brazil",      DateOfBirth = new DateTime(2004, 4, 10), MarketValue = 55.0,  Goals = 7,  Assists = 8,  CleanSheets = 0,  TotalPoints = 155 },
                new Player { Id = 27, FirstName = "Jeremy",   LastName = "Doku",        Position = Position.Forward,    Club = "Manchester City", Nationality = "Belgium",     DateOfBirth = new DateTime(2002, 5, 27), MarketValue = 65.0,  Goals = 8,  Assists = 7,  CleanSheets = 0,  TotalPoints = 148 },
                new Player { Id = 28, FirstName = "Oscar",    LastName = "Bobb",        Position = Position.Forward,    Club = "Manchester City", Nationality = "Norway",      DateOfBirth = new DateTime(2003, 7, 12), MarketValue = 30.0,  Goals = 6,  Assists = 4,  CleanSheets = 0,  TotalPoints = 112 },

                // ==========================================
                // LIVERPOOL (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 5,  FirstName = "Alisson",    LastName = "Becker",          Position = Position.Goalkeeper, Club = "Liverpool", Nationality = "Brazil",      DateOfBirth = new DateTime(1992, 10, 2),  MarketValue = 40.0,  Goals = 0,  Assists = 0,  CleanSheets = 16, TotalPoints = 165 },
                new Player { Id = 29, FirstName = "Caoimhin",   LastName = "Kelleher",        Position = Position.Goalkeeper, Club = "Liverpool", Nationality = "Ireland",     DateOfBirth = new DateTime(1998, 11, 23), MarketValue = 15.0,  Goals = 0,  Assists = 0,  CleanSheets = 5,  TotalPoints = 58 },
                new Player { Id = 4,  FirstName = "Virgil",     LastName = "van Dijk",        Position = Position.Defender,   Club = "Liverpool", Nationality = "Netherlands", DateOfBirth = new DateTime(1991, 7, 8),   MarketValue = 45.0,  Goals = 3,  Assists = 1,  CleanSheets = 15, TotalPoints = 180 },
                new Player { Id = 30, FirstName = "Trent",      LastName = "Alexander-Arnold", Position = Position.Defender,   Club = "Liverpool", Nationality = "England",    DateOfBirth = new DateTime(1998, 10, 7),  MarketValue = 70.0,  Goals = 2,  Assists = 10, CleanSheets = 13, TotalPoints = 175 },
                new Player { Id = 31, FirstName = "Andrew",     LastName = "Robertson",       Position = Position.Defender,   Club = "Liverpool", Nationality = "Scotland",    DateOfBirth = new DateTime(1994, 3, 11),  MarketValue = 25.0,  Goals = 1,  Assists = 7,  CleanSheets = 12, TotalPoints = 140 },
                new Player { Id = 32, FirstName = "Ibrahima",   LastName = "Konate",          Position = Position.Defender,   Club = "Liverpool", Nationality = "France",      DateOfBirth = new DateTime(1999, 5, 25),  MarketValue = 55.0,  Goals = 2,  Assists = 0,  CleanSheets = 14, TotalPoints = 148 },
                new Player { Id = 33, FirstName = "Joe",        LastName = "Gomez",           Position = Position.Defender,   Club = "Liverpool", Nationality = "England",     DateOfBirth = new DateTime(1997, 5, 23),  MarketValue = 28.0,  Goals = 0,  Assists = 1,  CleanSheets = 9,  TotalPoints = 98 },
                new Player { Id = 2,  FirstName = "Florian",    LastName = "Wirtz",           Position = Position.Midfielder, Club = "Liverpool", Nationality = "Germany",     DateOfBirth = new DateTime(2003, 5, 3),   MarketValue = 75.0,  Goals = 7,  Assists = 16, CleanSheets = 0,  TotalPoints = 210 },
                new Player { Id = 34, FirstName = "Dominik",    LastName = "Szoboszlai",      Position = Position.Midfielder, Club = "Liverpool", Nationality = "Hungary",     DateOfBirth = new DateTime(2000, 10, 25), MarketValue = 55.0,  Goals = 6,  Assists = 7,  CleanSheets = 0,  TotalPoints = 145 },
                new Player { Id = 35, FirstName = "Alexis",     LastName = "Mac Allister",    Position = Position.Midfielder, Club = "Liverpool", Nationality = "Argentina",   DateOfBirth = new DateTime(1998, 12, 24), MarketValue = 60.0,  Goals = 5,  Assists = 6,  CleanSheets = 0,  TotalPoints = 138 },
                new Player { Id = 36, FirstName = "Ryan",       LastName = "Gravenberch",     Position = Position.Midfielder, Club = "Liverpool", Nationality = "Netherlands", DateOfBirth = new DateTime(2002, 5, 16),  MarketValue = 45.0,  Goals = 3,  Assists = 4,  CleanSheets = 0,  TotalPoints = 122 },
                new Player { Id = 37, FirstName = "Curtis",     LastName = "Jones",           Position = Position.Midfielder, Club = "Liverpool", Nationality = "England",     DateOfBirth = new DateTime(2001, 1, 30),  MarketValue = 30.0,  Goals = 4,  Assists = 3,  CleanSheets = 0,  TotalPoints = 105 },
                new Player { Id = 3,  FirstName = "Mohamed",    LastName = "Salah",           Position = Position.Forward,    Club = "Liverpool", Nationality = "Egypt",       DateOfBirth = new DateTime(1992, 6, 15),  MarketValue = 70.0,  Goals = 19, Assists = 13, CleanSheets = 0,  TotalPoints = 250 },
                new Player { Id = 10, FirstName = "Alexander",  LastName = "Isak",            Position = Position.Forward,    Club = "Liverpool", Nationality = "Sweden",      DateOfBirth = new DateTime(1999, 9, 21),  MarketValue = 95.0,  Goals = 21, Assists = 3,  CleanSheets = 0,  TotalPoints = 230 },
                new Player { Id = 38, FirstName = "Luis",       LastName = "Diaz",            Position = Position.Forward,    Club = "Liverpool", Nationality = "Colombia",    DateOfBirth = new DateTime(1997, 1, 13),  MarketValue = 55.0,  Goals = 10, Assists = 5,  CleanSheets = 0,  TotalPoints = 148 },

                // ==========================================
                // ARSENAL (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 8,  FirstName = "David",    LastName = "Raya",         Position = Position.Goalkeeper, Club = "Arsenal", Nationality = "Spain",    DateOfBirth = new DateTime(1995, 9, 15),  MarketValue = 35.0,  Goals = 0,  Assists = 0,  CleanSheets = 13, TotalPoints = 155 },
                new Player { Id = 39, FirstName = "Karl",     LastName = "Hein",         Position = Position.Goalkeeper, Club = "Arsenal", Nationality = "Estonia",  DateOfBirth = new DateTime(2002, 4, 13),  MarketValue = 5.0,   Goals = 0,  Assists = 0,  CleanSheets = 3,  TotalPoints = 35 },
                new Player { Id = 7,  FirstName = "William",  LastName = "Saliba",       Position = Position.Defender,   Club = "Arsenal", Nationality = "France",   DateOfBirth = new DateTime(2001, 3, 24),  MarketValue = 90.0,  Goals = 2,  Assists = 1,  CleanSheets = 14, TotalPoints = 170 },
                new Player { Id = 40, FirstName = "Gabriel",  LastName = "Magalhaes",    Position = Position.Defender,   Club = "Arsenal", Nationality = "Brazil",   DateOfBirth = new DateTime(1997, 12, 19), MarketValue = 75.0,  Goals = 4,  Assists = 1,  CleanSheets = 13, TotalPoints = 162 },
                new Player { Id = 41, FirstName = "Ben",      LastName = "White",        Position = Position.Defender,   Club = "Arsenal", Nationality = "England",  DateOfBirth = new DateTime(1997, 10, 8),  MarketValue = 50.0,  Goals = 1,  Assists = 5,  CleanSheets = 12, TotalPoints = 142 },
                new Player { Id = 42, FirstName = "Jurrien",  LastName = "Timber",       Position = Position.Defender,   Club = "Arsenal", Nationality = "Netherlands", DateOfBirth = new DateTime(2001, 6, 17), MarketValue = 45.0,  Goals = 1,  Assists = 3,  CleanSheets = 11, TotalPoints = 128 },
                new Player { Id = 43, FirstName = "Riccardo", LastName = "Calafiori",    Position = Position.Defender,   Club = "Arsenal", Nationality = "Italy",    DateOfBirth = new DateTime(2002, 5, 19),  MarketValue = 42.0,  Goals = 1,  Assists = 2,  CleanSheets = 10, TotalPoints = 115 },
                new Player { Id = 6,  FirstName = "Bukayo",   LastName = "Saka",         Position = Position.Midfielder, Club = "Arsenal", Nationality = "England",  DateOfBirth = new DateTime(2001, 9, 5),   MarketValue = 120.0, Goals = 14, Assists = 11, CleanSheets = 0,  TotalPoints = 220 },
                new Player { Id = 44, FirstName = "Martin",   LastName = "Odegaard",     Position = Position.Midfielder, Club = "Arsenal", Nationality = "Norway",   DateOfBirth = new DateTime(1998, 12, 17), MarketValue = 100.0, Goals = 8,  Assists = 12, CleanSheets = 0,  TotalPoints = 195 },
                new Player { Id = 45, FirstName = "Declan",   LastName = "Rice",         Position = Position.Midfielder, Club = "Arsenal", Nationality = "England",  DateOfBirth = new DateTime(1999, 1, 14),  MarketValue = 95.0,  Goals = 5,  Assists = 6,  CleanSheets = 0,  TotalPoints = 158 },
                new Player { Id = 46, FirstName = "Kai",      LastName = "Havertz",      Position = Position.Midfielder, Club = "Arsenal", Nationality = "Germany",  DateOfBirth = new DateTime(1999, 6, 11),  MarketValue = 65.0,  Goals = 11, Assists = 5,  CleanSheets = 0,  TotalPoints = 172 },
                new Player { Id = 47, FirstName = "Thomas",   LastName = "Partey",       Position = Position.Midfielder, Club = "Arsenal", Nationality = "Ghana",    DateOfBirth = new DateTime(1993, 6, 13),  MarketValue = 25.0,  Goals = 2,  Assists = 3,  CleanSheets = 0,  TotalPoints = 95 },
                new Player { Id = 48, FirstName = "Gabriel",  LastName = "Jesus",        Position = Position.Forward,    Club = "Arsenal", Nationality = "Brazil",   DateOfBirth = new DateTime(1997, 4, 3),   MarketValue = 45.0,  Goals = 8,  Assists = 6,  CleanSheets = 0,  TotalPoints = 138 },
                new Player { Id = 49, FirstName = "Leandro",  LastName = "Trossard",     Position = Position.Forward,    Club = "Arsenal", Nationality = "Belgium",  DateOfBirth = new DateTime(1994, 12, 4),  MarketValue = 40.0,  Goals = 10, Assists = 4,  CleanSheets = 0,  TotalPoints = 145 },
                new Player { Id = 50, FirstName = "Eddie",    LastName = "Nketiah",      Position = Position.Forward,    Club = "Arsenal", Nationality = "England",  DateOfBirth = new DateTime(1999, 5, 30),  MarketValue = 28.0,  Goals = 6,  Assists = 2,  CleanSheets = 0,  TotalPoints = 95 },

                // ==========================================
                // CHELSEA (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 51, FirstName = "Robert",   LastName = "Sanchez",      Position = Position.Goalkeeper, Club = "Chelsea", Nationality = "Spain",    DateOfBirth = new DateTime(1997, 11, 18), MarketValue = 22.0,  Goals = 0,  Assists = 0,  CleanSheets = 9,  TotalPoints = 115 },
                new Player { Id = 52, FirstName = "Filip",    LastName = "Jorgensen",    Position = Position.Goalkeeper, Club = "Chelsea", Nationality = "Sweden",   DateOfBirth = new DateTime(2002, 4, 16),  MarketValue = 15.0,  Goals = 0,  Assists = 0,  CleanSheets = 4,  TotalPoints = 52 },
                new Player { Id = 53, FirstName = "Reece",    LastName = "James",        Position = Position.Defender,   Club = "Chelsea", Nationality = "England",  DateOfBirth = new DateTime(1999, 12, 8),  MarketValue = 40.0,  Goals = 1,  Assists = 4,  CleanSheets = 7,  TotalPoints = 108 },
                new Player { Id = 54, FirstName = "Wesley",   LastName = "Fofana",       Position = Position.Defender,   Club = "Chelsea", Nationality = "France",   DateOfBirth = new DateTime(2000, 12, 17), MarketValue = 45.0,  Goals = 1,  Assists = 0,  CleanSheets = 8,  TotalPoints = 105 },
                new Player { Id = 55, FirstName = "Levi",     LastName = "Colwill",      Position = Position.Defender,   Club = "Chelsea", Nationality = "England",  DateOfBirth = new DateTime(2003, 2, 26),  MarketValue = 50.0,  Goals = 2,  Assists = 2,  CleanSheets = 9,  TotalPoints = 125 },
                new Player { Id = 56, FirstName = "Marc",     LastName = "Cucurella",    Position = Position.Defender,   Club = "Chelsea", Nationality = "Spain",    DateOfBirth = new DateTime(1998, 7, 22),  MarketValue = 30.0,  Goals = 1,  Assists = 5,  CleanSheets = 8,  TotalPoints = 118 },
                new Player { Id = 57, FirstName = "Benoit",   LastName = "Badiashile",   Position = Position.Defender,   Club = "Chelsea", Nationality = "France",   DateOfBirth = new DateTime(2001, 3, 26),  MarketValue = 28.0,  Goals = 0,  Assists = 1,  CleanSheets = 7,  TotalPoints = 82 },
                new Player { Id = 9,  FirstName = "Cole",     LastName = "Palmer",       Position = Position.Midfielder, Club = "Chelsea", Nationality = "England",  DateOfBirth = new DateTime(2002, 5, 6),   MarketValue = 110.0, Goals = 22, Assists = 11, CleanSheets = 0,  TotalPoints = 260 },
                new Player { Id = 58, FirstName = "Enzo",     LastName = "Fernandez",    Position = Position.Midfielder, Club = "Chelsea", Nationality = "Argentina", DateOfBirth = new DateTime(2001, 1, 17), MarketValue = 65.0,  Goals = 4,  Assists = 7,  CleanSheets = 0,  TotalPoints = 135 },
                new Player { Id = 59, FirstName = "Moises",   LastName = "Caicedo",      Position = Position.Midfielder, Club = "Chelsea", Nationality = "Ecuador",  DateOfBirth = new DateTime(2001, 11, 2),  MarketValue = 70.0,  Goals = 3,  Assists = 4,  CleanSheets = 0,  TotalPoints = 120 },
                new Player { Id = 60, FirstName = "Romeo",    LastName = "Lavia",        Position = Position.Midfielder, Club = "Chelsea", Nationality = "Belgium",  DateOfBirth = new DateTime(2004, 1, 6),   MarketValue = 45.0,  Goals = 1,  Assists = 3,  CleanSheets = 0,  TotalPoints = 88 },
                new Player { Id = 61, FirstName = "Noni",     LastName = "Madueke",      Position = Position.Midfielder, Club = "Chelsea", Nationality = "England",  DateOfBirth = new DateTime(2002, 3, 10),  MarketValue = 55.0,  Goals = 9,  Assists = 6,  CleanSheets = 0,  TotalPoints = 158 },
                new Player { Id = 62, FirstName = "Nicolas",  LastName = "Jackson",      Position = Position.Forward,    Club = "Chelsea", Nationality = "Senegal",  DateOfBirth = new DateTime(2001, 6, 20),  MarketValue = 50.0,  Goals = 14, Assists = 5,  CleanSheets = 0,  TotalPoints = 168 },
                new Player { Id = 63, FirstName = "Christopher", LastName = "Nkunku",    Position = Position.Forward,    Club = "Chelsea", Nationality = "France",   DateOfBirth = new DateTime(1997, 11, 14), MarketValue = 60.0,  Goals = 11, Assists = 4,  CleanSheets = 0,  TotalPoints = 145 },
                new Player { Id = 64, FirstName = "Mykhailo", LastName = "Mudryk",       Position = Position.Forward,    Club = "Chelsea", Nationality = "Ukraine",  DateOfBirth = new DateTime(2001, 1, 5),   MarketValue = 30.0,  Goals = 5,  Assists = 3,  CleanSheets = 0,  TotalPoints = 88 },

                // ==========================================
                // MANCHESTER UNITED (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 65, FirstName = "Andre",     LastName = "Onana",        Position = Position.Goalkeeper, Club = "Manchester United", Nationality = "Cameroon",    DateOfBirth = new DateTime(1996, 4, 2),   MarketValue = 28.0,  Goals = 0,  Assists = 0,  CleanSheets = 8,  TotalPoints = 108 },
                new Player { Id = 66, FirstName = "Altay",     LastName = "Bayindir",     Position = Position.Goalkeeper, Club = "Manchester United", Nationality = "Turkey",      DateOfBirth = new DateTime(1998, 4, 14),  MarketValue = 8.0,   Goals = 0,  Assists = 0,  CleanSheets = 3,  TotalPoints = 38 },
                new Player { Id = 67, FirstName = "Lisandro",  LastName = "Martinez",     Position = Position.Defender,   Club = "Manchester United", Nationality = "Argentina",   DateOfBirth = new DateTime(1998, 1, 18),  MarketValue = 50.0,  Goals = 2,  Assists = 1,  CleanSheets = 7,  TotalPoints = 115 },
                new Player { Id = 68, FirstName = "Matthijs",  LastName = "de Ligt",      Position = Position.Defender,   Club = "Manchester United", Nationality = "Netherlands", DateOfBirth = new DateTime(1999, 8, 12),  MarketValue = 35.0,  Goals = 1,  Assists = 0,  CleanSheets = 6,  TotalPoints = 92 },
                new Player { Id = 69, FirstName = "Diogo",     LastName = "Dalot",        Position = Position.Defender,   Club = "Manchester United", Nationality = "Portugal",    DateOfBirth = new DateTime(1999, 3, 18),  MarketValue = 38.0,  Goals = 1,  Assists = 4,  CleanSheets = 7,  TotalPoints = 110 },
                new Player { Id = 70, FirstName = "Luke",      LastName = "Shaw",         Position = Position.Defender,   Club = "Manchester United", Nationality = "England",     DateOfBirth = new DateTime(1995, 7, 12),  MarketValue = 20.0,  Goals = 0,  Assists = 3,  CleanSheets = 5,  TotalPoints = 78 },
                new Player { Id = 71, FirstName = "Harry",     LastName = "Maguire",      Position = Position.Defender,   Club = "Manchester United", Nationality = "England",     DateOfBirth = new DateTime(1993, 3, 5),   MarketValue = 15.0,  Goals = 2,  Assists = 0,  CleanSheets = 6,  TotalPoints = 85 },
                new Player { Id = 11, FirstName = "Bruno",     LastName = "Fernandes",    Position = Position.Midfielder, Club = "Manchester United", Nationality = "Portugal",    DateOfBirth = new DateTime(1994, 9, 8),   MarketValue = 60.0,  Goals = 8,  Assists = 8,  CleanSheets = 0,  TotalPoints = 155 },
                new Player { Id = 72, FirstName = "Kobbie",    LastName = "Mainoo",       Position = Position.Midfielder, Club = "Manchester United", Nationality = "England",     DateOfBirth = new DateTime(2005, 4, 19),  MarketValue = 55.0,  Goals = 3,  Assists = 5,  CleanSheets = 0,  TotalPoints = 118 },
                new Player { Id = 73, FirstName = "Mason",     LastName = "Mount",        Position = Position.Midfielder, Club = "Manchester United", Nationality = "England",     DateOfBirth = new DateTime(1999, 1, 10),  MarketValue = 25.0,  Goals = 2,  Assists = 3,  CleanSheets = 0,  TotalPoints = 72 },
                new Player { Id = 74, FirstName = "Amad",      LastName = "Diallo",       Position = Position.Midfielder, Club = "Manchester United", Nationality = "Ivory Coast", DateOfBirth = new DateTime(2002, 7, 11),  MarketValue = 40.0,  Goals = 7,  Assists = 6,  CleanSheets = 0,  TotalPoints = 142 },
                new Player { Id = 75, FirstName = "Alejandro",  LastName = "Garnacho",     Position = Position.Midfielder, Club = "Manchester United", Nationality = "Argentina",      DateOfBirth = new DateTime(1992, 2, 23),  MarketValue = 12.0,  Goals = 1,  Assists = 2,  CleanSheets = 0,  TotalPoints = 65 },
                new Player { Id = 15, FirstName = "Joshua",  LastName = "Zirkzee",        Position = Position.Forward,    Club = "Manchester United", Nationality = "Netherlands",    DateOfBirth = new DateTime(2003, 5, 31),  MarketValue = 50.0,  Goals = 12, Assists = 7,  CleanSheets = 0,  TotalPoints = 175 },
                new Player { Id = 76, FirstName = "Marcus",    LastName = "Rashford",     Position = Position.Forward,    Club = "Manchester United", Nationality = "England",     DateOfBirth = new DateTime(1997, 10, 31), MarketValue = 45.0,  Goals = 7,  Assists = 3,  CleanSheets = 0,  TotalPoints = 105 },
                new Player { Id = 77, FirstName = "Rasmus",    LastName = "Hojlund",      Position = Position.Forward,    Club = "Manchester United", Nationality = "Denmark",     DateOfBirth = new DateTime(2003, 2, 4),   MarketValue = 40.0,  Goals = 10, Assists = 2,  CleanSheets = 0,  TotalPoints = 128 },

                // ==========================================
                // NEWCASTLE (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 12, FirstName = "Nick",      LastName = "Pope",         Position = Position.Goalkeeper, Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(1992, 4, 19),  MarketValue = 20.0,  Goals = 0,  Assists = 0,  CleanSheets = 10, TotalPoints = 130 },
                new Player { Id = 78, FirstName = "Martin",    LastName = "Dubravka",     Position = Position.Goalkeeper, Club = "Newcastle", Nationality = "Slovakia",    DateOfBirth = new DateTime(1989, 1, 15),  MarketValue = 5.0,   Goals = 0,  Assists = 0,  CleanSheets = 3,  TotalPoints = 35 },
                new Player { Id = 79, FirstName = "Kieran",    LastName = "Trippier",     Position = Position.Defender,   Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(1990, 9, 19),  MarketValue = 15.0,  Goals = 1,  Assists = 6,  CleanSheets = 8,  TotalPoints = 118 },
                new Player { Id = 80, FirstName = "Sven",      LastName = "Botman",       Position = Position.Defender,   Club = "Newcastle", Nationality = "Netherlands", DateOfBirth = new DateTime(2000, 1, 12),  MarketValue = 45.0,  Goals = 1,  Assists = 0,  CleanSheets = 9,  TotalPoints = 112 },
                new Player { Id = 81, FirstName = "Dan",       LastName = "Burn",         Position = Position.Defender,   Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(1992, 5, 9),   MarketValue = 12.0,  Goals = 2,  Assists = 1,  CleanSheets = 8,  TotalPoints = 105 },
                new Player { Id = 82, FirstName = "Fabian",    LastName = "Schar",        Position = Position.Defender,   Club = "Newcastle", Nationality = "Switzerland", DateOfBirth = new DateTime(1991, 12, 20), MarketValue = 10.0,  Goals = 1,  Assists = 0,  CleanSheets = 7,  TotalPoints = 88 },
                new Player { Id = 83, FirstName = "Lewis",     LastName = "Hall",         Position = Position.Defender,   Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(2004, 9, 8),   MarketValue = 25.0,  Goals = 0,  Assists = 4,  CleanSheets = 7,  TotalPoints = 95 },
                new Player { Id = 84, FirstName = "Bruno",     LastName = "Guimaraes",    Position = Position.Midfielder, Club = "Newcastle", Nationality = "Brazil",      DateOfBirth = new DateTime(1997, 11, 16), MarketValue = 80.0,  Goals = 6,  Assists = 7,  CleanSheets = 0,  TotalPoints = 155 },
                new Player { Id = 85, FirstName = "Joelinton", LastName = "Cassio",       Position = Position.Midfielder, Club = "Newcastle", Nationality = "Brazil",      DateOfBirth = new DateTime(1996, 8, 14),  MarketValue = 35.0,  Goals = 4,  Assists = 3,  CleanSheets = 0,  TotalPoints = 108 },
                new Player { Id = 86, FirstName = "Anthony",   LastName = "Gordon",       Position = Position.Midfielder, Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(2001, 2, 24),  MarketValue = 60.0,  Goals = 10, Assists = 6,  CleanSheets = 0,  TotalPoints = 168 },
                new Player { Id = 87, FirstName = "Sean",      LastName = "Longstaff",    Position = Position.Midfielder, Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(1997, 10, 30), MarketValue = 18.0,  Goals = 2,  Assists = 3,  CleanSheets = 0,  TotalPoints = 78 },
                new Player { Id = 88, FirstName = "Joe",       LastName = "Willock",      Position = Position.Midfielder, Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(1999, 8, 20),  MarketValue = 20.0,  Goals = 3,  Assists = 2,  CleanSheets = 0,  TotalPoints = 82 },
                new Player { Id = 89, FirstName = "Callum",    LastName = "Wilson",       Position = Position.Forward,    Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(1992, 2, 27),  MarketValue = 15.0,  Goals = 7,  Assists = 3,  CleanSheets = 0,  TotalPoints = 108 },
                new Player { Id = 90, FirstName = "Harvey",    LastName = "Barnes",       Position = Position.Forward,    Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(1997, 12, 9),  MarketValue = 30.0,  Goals = 8,  Assists = 5,  CleanSheets = 0,  TotalPoints = 128 },
                new Player { Id = 91, FirstName = "Miguel",    LastName = "Almiron",      Position = Position.Forward,    Club = "Newcastle", Nationality = "Paraguay",    DateOfBirth = new DateTime(1994, 2, 10),  MarketValue = 18.0,  Goals = 5,  Assists = 4,  CleanSheets = 0,  TotalPoints = 92 },

                // ==========================================
                // ASTON VILLA (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 92,  FirstName = "Emiliano",  LastName = "Martinez",     Position = Position.Goalkeeper, Club = "Aston Villa", Nationality = "Argentina",   DateOfBirth = new DateTime(1992, 9, 2),   MarketValue = 35.0,  Goals = 0,  Assists = 0,  CleanSheets = 12, TotalPoints = 148 },
                new Player { Id = 93,  FirstName = "Robin",     LastName = "Olsen",        Position = Position.Goalkeeper, Club = "Aston Villa", Nationality = "Sweden",      DateOfBirth = new DateTime(1990, 1, 8),   MarketValue = 3.0,   Goals = 0,  Assists = 0,  CleanSheets = 2,  TotalPoints = 28 },
                new Player { Id = 94,  FirstName = "Ezri",      LastName = "Konsa",        Position = Position.Defender,   Club = "Aston Villa", Nationality = "England",     DateOfBirth = new DateTime(1997, 10, 23), MarketValue = 40.0,  Goals = 2,  Assists = 1,  CleanSheets = 10, TotalPoints = 128 },
                new Player { Id = 95,  FirstName = "Pau",       LastName = "Torres",       Position = Position.Defender,   Club = "Aston Villa", Nationality = "Spain",       DateOfBirth = new DateTime(1997, 1, 16),  MarketValue = 42.0,  Goals = 1,  Assists = 2,  CleanSheets = 10, TotalPoints = 122 },
                new Player { Id = 96,  FirstName = "Lucas",     LastName = "Digne",        Position = Position.Defender,   Club = "Aston Villa", Nationality = "France",      DateOfBirth = new DateTime(1993, 7, 20),  MarketValue = 15.0,  Goals = 1,  Assists = 5,  CleanSheets = 8,  TotalPoints = 110 },
                new Player { Id = 97,  FirstName = "Matty",     LastName = "Cash",         Position = Position.Defender,   Club = "Aston Villa", Nationality = "Poland",      DateOfBirth = new DateTime(1997, 8, 7),   MarketValue = 22.0,  Goals = 1,  Assists = 4,  CleanSheets = 8,  TotalPoints = 105 },
                new Player { Id = 98,  FirstName = "Tyrone",    LastName = "Mings",        Position = Position.Defender,   Club = "Aston Villa", Nationality = "England",     DateOfBirth = new DateTime(1993, 3, 13),  MarketValue = 12.0,  Goals = 1,  Assists = 0,  CleanSheets = 7,  TotalPoints = 82 },
                new Player { Id = 99,  FirstName = "John",      LastName = "McGinn",       Position = Position.Midfielder, Club = "Aston Villa", Nationality = "Scotland",    DateOfBirth = new DateTime(1994, 10, 18), MarketValue = 38.0,  Goals = 6,  Assists = 5,  CleanSheets = 0,  TotalPoints = 138 },
                new Player { Id = 100, FirstName = "Youri",     LastName = "Tielemans",    Position = Position.Midfielder, Club = "Aston Villa", Nationality = "Belgium",     DateOfBirth = new DateTime(1997, 5, 7),   MarketValue = 30.0,  Goals = 4,  Assists = 6,  CleanSheets = 0,  TotalPoints = 125 },
                new Player { Id = 101, FirstName = "Morgan",    LastName = "Rogers",       Position = Position.Midfielder, Club = "Aston Villa", Nationality = "England",     DateOfBirth = new DateTime(2002, 7, 26),  MarketValue = 35.0,  Goals = 8,  Assists = 5,  CleanSheets = 0,  TotalPoints = 148 },
                new Player { Id = 102, FirstName = "Leon",      LastName = "Bailey",       Position = Position.Midfielder, Club = "Aston Villa", Nationality = "Jamaica",     DateOfBirth = new DateTime(1997, 8, 9),   MarketValue = 28.0,  Goals = 7,  Assists = 4,  CleanSheets = 0,  TotalPoints = 128 },
                new Player { Id = 103, FirstName = "Jacob",     LastName = "Ramsey",       Position = Position.Midfielder, Club = "Aston Villa", Nationality = "England",     DateOfBirth = new DateTime(2001, 5, 28),  MarketValue = 25.0,  Goals = 3,  Assists = 3,  CleanSheets = 0,  TotalPoints = 88 },
                new Player { Id = 14, FirstName = "Ollie",      LastName = "Watkins",      Position = Position.Forward,    Club = "Aston Villa", Nationality = "England",     DateOfBirth = new DateTime(1995, 12, 30), MarketValue = 65.0,  Goals = 15, Assists = 9,  CleanSheets = 0,  TotalPoints = 195 },
                new Player { Id = 104, FirstName = "Jhon",      LastName = "Duran",        Position = Position.Forward,    Club = "Aston Villa", Nationality = "Colombia",    DateOfBirth = new DateTime(2003, 12, 13), MarketValue = 35.0,  Goals = 10, Assists = 2,  CleanSheets = 0,  TotalPoints = 128 },
                new Player { Id = 105, FirstName = "Moussa",    LastName = "Diaby",        Position = Position.Forward,    Club = "Aston Villa", Nationality = "France",      DateOfBirth = new DateTime(1999, 7, 7),   MarketValue = 42.0,  Goals = 7,  Assists = 6,  CleanSheets = 0,  TotalPoints = 118 },

                // ==========================================
                // TOTTENHAM (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 106, FirstName = "Guglielmo", LastName = "Vicario",      Position = Position.Goalkeeper, Club = "Tottenham", Nationality = "Italy",        DateOfBirth = new DateTime(1996, 10, 7),  MarketValue = 32.0,  Goals = 0,  Assists = 0,  CleanSheets = 11, TotalPoints = 138 },
                new Player { Id = 107, FirstName = "Antonin",   LastName = "Kinsky",       Position = Position.Goalkeeper, Club = "Tottenham", Nationality = "Czech Republic", DateOfBirth = new DateTime(2003, 5, 22), MarketValue = 12.0,  Goals = 0,  Assists = 0,  CleanSheets = 4,  TotalPoints = 55 },
                new Player { Id = 108, FirstName = "Cristian",  LastName = "Romero",       Position = Position.Defender,   Club = "Tottenham", Nationality = "Argentina",    DateOfBirth = new DateTime(1998, 4, 27),  MarketValue = 55.0,  Goals = 3,  Assists = 1,  CleanSheets = 10, TotalPoints = 142 },
                new Player { Id = 109, FirstName = "Micky",     LastName = "van de Ven",   Position = Position.Defender,   Club = "Tottenham", Nationality = "Netherlands",  DateOfBirth = new DateTime(2001, 4, 19),  MarketValue = 50.0,  Goals = 2,  Assists = 2,  CleanSheets = 10, TotalPoints = 135 },
                new Player { Id = 110, FirstName = "Pedro",     LastName = "Porro",        Position = Position.Defender,   Club = "Tottenham", Nationality = "Spain",        DateOfBirth = new DateTime(1999, 9, 13),  MarketValue = 45.0,  Goals = 3,  Assists = 6,  CleanSheets = 8,  TotalPoints = 138 },
                new Player { Id = 111, FirstName = "Destiny",   LastName = "Udogie",       Position = Position.Defender,   Club = "Tottenham", Nationality = "Italy",        DateOfBirth = new DateTime(2002, 11, 28), MarketValue = 38.0,  Goals = 1,  Assists = 4,  CleanSheets = 8,  TotalPoints = 118 },
                new Player { Id = 112, FirstName = "Kevin",     LastName = "Danso",        Position = Position.Defender,   Club = "Tottenham", Nationality = "Austria",      DateOfBirth = new DateTime(1998, 9, 19),  MarketValue = 25.0,  Goals = 1,  Assists = 0,  CleanSheets = 7,  TotalPoints = 88 },
                new Player { Id = 113, FirstName = "James",     LastName = "Maddison",     Position = Position.Midfielder, Club = "Tottenham", Nationality = "England",      DateOfBirth = new DateTime(1996, 11, 23), MarketValue = 55.0,  Goals = 9,  Assists = 10, CleanSheets = 0,  TotalPoints = 165 },
                new Player { Id = 114, FirstName = "Dejan",     LastName = "Kulusevski",   Position = Position.Midfielder, Club = "Tottenham", Nationality = "Sweden",       DateOfBirth = new DateTime(2000, 4, 25),  MarketValue = 50.0,  Goals = 7,  Assists = 8,  CleanSheets = 0,  TotalPoints = 152 },
                new Player { Id = 115, FirstName = "Pape",      LastName = "Sarr",         Position = Position.Midfielder, Club = "Tottenham", Nationality = "Senegal",      DateOfBirth = new DateTime(2002, 9, 14),  MarketValue = 35.0,  Goals = 3,  Assists = 4,  CleanSheets = 0,  TotalPoints = 108 },
                new Player { Id = 116, FirstName = "Rodrigo",   LastName = "Bentancur",    Position = Position.Midfielder, Club = "Tottenham", Nationality = "Uruguay",      DateOfBirth = new DateTime(1997, 6, 25),  MarketValue = 30.0,  Goals = 2,  Assists = 2,  CleanSheets = 0,  TotalPoints = 95 },
                new Player { Id = 117, FirstName = "Lucas",     LastName = "Bergvall",     Position = Position.Midfielder, Club = "Tottenham", Nationality = "Sweden",       DateOfBirth = new DateTime(2006, 2, 2),   MarketValue = 28.0,  Goals = 2,  Assists = 3,  CleanSheets = 0,  TotalPoints = 92 },
                new Player { Id = 118, FirstName = "Dominic",   LastName = "Solanke",      Position = Position.Forward,    Club = "Tottenham", Nationality = "England",      DateOfBirth = new DateTime(1997, 9, 14),  MarketValue = 55.0,  Goals = 14, Assists = 5,  CleanSheets = 0,  TotalPoints = 168 },
                new Player { Id = 119, FirstName = "Brennan",   LastName = "Johnson",      Position = Position.Forward,    Club = "Tottenham", Nationality = "Wales",        DateOfBirth = new DateTime(2001, 5, 23),  MarketValue = 42.0,  Goals = 11, Assists = 6,  CleanSheets = 0,  TotalPoints = 148 },
                new Player { Id = 120, FirstName = "Richarlison", LastName = "Andrade",    Position = Position.Forward,    Club = "Tottenham", Nationality = "Brazil",       DateOfBirth = new DateTime(1997, 5, 10),  MarketValue = 35.0,  Goals = 7,  Assists = 3,  CleanSheets = 0,  TotalPoints = 102 },

                // ==========================================
                // WEST HAM (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 121, FirstName = "Alphonse",  LastName = "Areola",       Position = Position.Goalkeeper, Club = "West Ham", Nationality = "France",        DateOfBirth = new DateTime(1993, 2, 27),  MarketValue = 18.0,  Goals = 0,  Assists = 0,  CleanSheets = 8,  TotalPoints = 112 },
                new Player { Id = 122, FirstName = "Lukasz",    LastName = "Fabianski",    Position = Position.Goalkeeper, Club = "West Ham", Nationality = "Poland",        DateOfBirth = new DateTime(1985, 4, 18),  MarketValue = 4.0,   Goals = 0,  Assists = 0,  CleanSheets = 2,  TotalPoints = 30 },
                new Player { Id = 123, FirstName = "Max",       LastName = "Kilman",       Position = Position.Defender,   Club = "West Ham", Nationality = "England",       DateOfBirth = new DateTime(1997, 5, 23),  MarketValue = 28.0,  Goals = 1,  Assists = 1,  CleanSheets = 7,  TotalPoints = 98 },
                new Player { Id = 124, FirstName = "Jean-Clair", LastName = "Todibo",      Position = Position.Defender,   Club = "West Ham", Nationality = "France",        DateOfBirth = new DateTime(1999, 12, 30), MarketValue = 30.0,  Goals = 0,  Assists = 1,  CleanSheets = 7,  TotalPoints = 95 },
                new Player { Id = 125, FirstName = "Aaron",     LastName = "Wan-Bissaka",  Position = Position.Defender,   Club = "West Ham", Nationality = "England",       DateOfBirth = new DateTime(1997, 11, 26), MarketValue = 32.0,  Goals = 1,  Assists = 4,  CleanSheets = 7,  TotalPoints = 110 },
                new Player { Id = 126, FirstName = "Emerson",   LastName = "Palmieri",     Position = Position.Defender,   Club = "West Ham", Nationality = "Italy",         DateOfBirth = new DateTime(1994, 8, 3),   MarketValue = 22.0,  Goals = 1,  Assists = 3,  CleanSheets = 6,  TotalPoints = 95 },
                new Player { Id = 127, FirstName = "Konstantinos", LastName = "Mavropanos", Position = Position.Defender,  Club = "West Ham", Nationality = "Greece",        DateOfBirth = new DateTime(1997, 12, 11), MarketValue = 18.0,  Goals = 1,  Assists = 0,  CleanSheets = 6,  TotalPoints = 78 },
                new Player { Id = 128, FirstName = "Lucas",     LastName = "Paqueta",      Position = Position.Midfielder, Club = "West Ham", Nationality = "Brazil",        DateOfBirth = new DateTime(1997, 8, 27),  MarketValue = 45.0,  Goals = 5,  Assists = 7,  CleanSheets = 0,  TotalPoints = 135 },
                new Player { Id = 129, FirstName = "Tomas",     LastName = "Soucek",       Position = Position.Midfielder, Club = "West Ham", Nationality = "Czech Republic", DateOfBirth = new DateTime(1995, 2, 27), MarketValue = 28.0,  Goals = 6,  Assists = 2,  CleanSheets = 0,  TotalPoints = 118 },
                new Player { Id = 130, FirstName = "Edson",     LastName = "Alvarez",      Position = Position.Midfielder, Club = "West Ham", Nationality = "Mexico",        DateOfBirth = new DateTime(1997, 10, 24), MarketValue = 25.0,  Goals = 1,  Assists = 1,  CleanSheets = 0,  TotalPoints = 82 },
                new Player { Id = 131, FirstName = "James",     LastName = "Ward-Prowse",  Position = Position.Midfielder, Club = "West Ham", Nationality = "England",       DateOfBirth = new DateTime(1994, 11, 1),  MarketValue = 30.0,  Goals = 4,  Assists = 6,  CleanSheets = 0,  TotalPoints = 122 },
                new Player { Id = 132, FirstName = "Guido",     LastName = "Rodriguez",    Position = Position.Midfielder, Club = "West Ham", Nationality = "Argentina",     DateOfBirth = new DateTime(1994, 4, 12),  MarketValue = 18.0,  Goals = 1,  Assists = 1,  CleanSheets = 0,  TotalPoints = 70 },
                new Player { Id = 133, FirstName = "Jarrod",    LastName = "Bowen",        Position = Position.Forward,    Club = "West Ham", Nationality = "England",       DateOfBirth = new DateTime(1996, 12, 20), MarketValue = 55.0,  Goals = 13, Assists = 8,  CleanSheets = 0,  TotalPoints = 172 },
                new Player { Id = 134, FirstName = "Niclas",    LastName = "Fullkrug",     Position = Position.Forward,    Club = "West Ham", Nationality = "Germany",       DateOfBirth = new DateTime(1993, 2, 9),   MarketValue = 32.0,  Goals = 9,  Assists = 3,  CleanSheets = 0,  TotalPoints = 118 },
                new Player { Id = 135, FirstName = "Crysencio", LastName = "Summerville",  Position = Position.Forward,    Club = "West Ham", Nationality = "Netherlands",   DateOfBirth = new DateTime(2001, 10, 30), MarketValue = 30.0,  Goals = 6,  Assists = 4,  CleanSheets = 0,  TotalPoints = 105 },

                // ==========================================
                // BRIGHTON (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 136, FirstName = "Bart",      LastName = "Verbruggen",   Position = Position.Goalkeeper, Club = "Brighton", Nationality = "Netherlands",   DateOfBirth = new DateTime(2002, 8, 18),  MarketValue = 22.0,  Goals = 0,  Assists = 0,  CleanSheets = 9,  TotalPoints = 120 },
                new Player { Id = 137, FirstName = "Jason",     LastName = "Steele",       Position = Position.Goalkeeper, Club = "Brighton", Nationality = "England",       DateOfBirth = new DateTime(1990, 8, 18),  MarketValue = 3.0,   Goals = 0,  Assists = 0,  CleanSheets = 2,  TotalPoints = 28 },
                new Player { Id = 138, FirstName = "Lewis",     LastName = "Dunk",         Position = Position.Defender,   Club = "Brighton", Nationality = "England",       DateOfBirth = new DateTime(1991, 11, 21), MarketValue = 28.0,  Goals = 2,  Assists = 1,  CleanSheets = 8,  TotalPoints = 105 },
                new Player { Id = 139, FirstName = "Jan Paul",  LastName = "van Hecke",    Position = Position.Defender,   Club = "Brighton", Nationality = "Netherlands",   DateOfBirth = new DateTime(2000, 6, 8),   MarketValue = 30.0,  Goals = 1,  Assists = 1,  CleanSheets = 8,  TotalPoints = 102 },
                new Player { Id = 140, FirstName = "Pervis",    LastName = "Estupinan",    Position = Position.Defender,   Club = "Brighton", Nationality = "Ecuador",       DateOfBirth = new DateTime(1998, 1, 21),  MarketValue = 30.0,  Goals = 1,  Assists = 4,  CleanSheets = 7,  TotalPoints = 108 },
                new Player { Id = 141, FirstName = "Tariq",     LastName = "Lamptey",      Position = Position.Defender,   Club = "Brighton", Nationality = "Ghana",         DateOfBirth = new DateTime(2000, 9, 30),  MarketValue = 18.0,  Goals = 0,  Assists = 3,  CleanSheets = 6,  TotalPoints = 82 },
                new Player { Id = 142, FirstName = "Igor",      LastName = "Julio",        Position = Position.Defender,   Club = "Brighton", Nationality = "Brazil",        DateOfBirth = new DateTime(1998, 2, 7),   MarketValue = 18.0,  Goals = 1,  Assists = 0,  CleanSheets = 6,  TotalPoints = 78 },
                new Player { Id = 143, FirstName = "Kaoru",     LastName = "Mitoma",       Position = Position.Midfielder, Club = "Brighton", Nationality = "Japan",         DateOfBirth = new DateTime(1997, 5, 20),  MarketValue = 50.0,  Goals = 10, Assists = 7,  CleanSheets = 0,  TotalPoints = 158 },
                new Player { Id = 144, FirstName = "Yankuba",   LastName = "Minteh",       Position = Position.Midfielder, Club = "Brighton", Nationality = "Gambia",        DateOfBirth = new DateTime(2004, 7, 22),  MarketValue = 38.0,  Goals = 7,  Assists = 5,  CleanSheets = 0,  TotalPoints = 132 },
                new Player { Id = 145, FirstName = "Carlos",    LastName = "Baleba",       Position = Position.Midfielder, Club = "Brighton", Nationality = "Cameroon",      DateOfBirth = new DateTime(2004, 1, 3),   MarketValue = 45.0,  Goals = 2,  Assists = 3,  CleanSheets = 0,  TotalPoints = 110 },
                new Player { Id = 146, FirstName = "James",     LastName = "Milner",       Position = Position.Midfielder, Club = "Brighton", Nationality = "England",       DateOfBirth = new DateTime(1986, 1, 4),   MarketValue = 5.0,   Goals = 1,  Assists = 2,  CleanSheets = 0,  TotalPoints = 58 },
                new Player { Id = 147, FirstName = "Yasin",     LastName = "Ayari",        Position = Position.Midfielder, Club = "Brighton", Nationality = "Sweden",        DateOfBirth = new DateTime(2003, 10, 6),  MarketValue = 22.0,  Goals = 2,  Assists = 2,  CleanSheets = 0,  TotalPoints = 80 },
                new Player { Id = 148, FirstName = "Danny",     LastName = "Welbeck",      Position = Position.Forward,    Club = "Brighton", Nationality = "England",       DateOfBirth = new DateTime(1990, 11, 26), MarketValue = 25.0,  Goals = 9,  Assists = 4,  CleanSheets = 0,  TotalPoints = 118 },
                new Player { Id = 149, FirstName = "Georginio", LastName = "Rutter",       Position = Position.Forward,    Club = "Brighton", Nationality = "France",        DateOfBirth = new DateTime(2002, 4, 20),  MarketValue = 35.0,  Goals = 8,  Assists = 6,  CleanSheets = 0,  TotalPoints = 125 },
                new Player { Id = 150, FirstName = "Simon",     LastName = "Adingra",      Position = Position.Forward,    Club = "Brighton", Nationality = "Ivory Coast",   DateOfBirth = new DateTime(2002, 1, 1),   MarketValue = 28.0,  Goals = 5,  Assists = 4,  CleanSheets = 0,  TotalPoints = 98 },

                // ==========================================
                // WOLVES (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 151, FirstName = "Jose",      LastName = "Sa",           Position = Position.Goalkeeper, Club = "Wolverhampton", Nationality = "Portugal",  DateOfBirth = new DateTime(1993, 1, 17),  MarketValue = 18.0,  Goals = 0,  Assists = 0,  CleanSheets = 7,  TotalPoints = 105 },
                new Player { Id = 152, FirstName = "Daniel",    LastName = "Bentley",      Position = Position.Goalkeeper, Club = "Wolverhampton", Nationality = "England",   DateOfBirth = new DateTime(1993, 7, 13),  MarketValue = 3.0,   Goals = 0,  Assists = 0,  CleanSheets = 2,  TotalPoints = 28 },
                new Player { Id = 153, FirstName = "Toti",      LastName = "Gomes",        Position = Position.Defender,   Club = "Wolverhampton", Nationality = "Portugal",  DateOfBirth = new DateTime(1999, 1, 16),  MarketValue = 20.0,  Goals = 1,  Assists = 1,  CleanSheets = 6,  TotalPoints = 85 },
                new Player { Id = 154, FirstName = "Craig",     LastName = "Dawson",       Position = Position.Defender,   Club = "Wolverhampton", Nationality = "England",   DateOfBirth = new DateTime(1990, 5, 6),   MarketValue = 8.0,   Goals = 1,  Assists = 0,  CleanSheets = 5,  TotalPoints = 65 },
                new Player { Id = 155, FirstName = "Rayan",     LastName = "Ait-Nouri",    Position = Position.Defender,   Club = "Wolverhampton", Nationality = "Algeria",   DateOfBirth = new DateTime(2001, 6, 6),   MarketValue = 32.0,  Goals = 2,  Assists = 5,  CleanSheets = 6,  TotalPoints = 118 },
                new Player { Id = 156, FirstName = "Matt",      LastName = "Doherty",      Position = Position.Defender,   Club = "Wolverhampton", Nationality = "Ireland",   DateOfBirth = new DateTime(1992, 1, 16),  MarketValue = 10.0,  Goals = 0,  Assists = 2,  CleanSheets = 5,  TotalPoints = 72 },
                new Player { Id = 157, FirstName = "Santiago",  LastName = "Bueno",        Position = Position.Defender,   Club = "Wolverhampton", Nationality = "Uruguay",   DateOfBirth = new DateTime(1998, 11, 9),  MarketValue = 15.0,  Goals = 1,  Assists = 0,  CleanSheets = 5,  TotalPoints = 70 },
                new Player { Id = 158, FirstName = "Joao",      LastName = "Gomes",        Position = Position.Midfielder, Club = "Wolverhampton", Nationality = "Brazil",    DateOfBirth = new DateTime(2001, 2, 12),  MarketValue = 35.0,  Goals = 3,  Assists = 4,  CleanSheets = 0,  TotalPoints = 112 },
                new Player { Id = 159, FirstName = "Mario",     LastName = "Lemina",       Position = Position.Midfielder, Club = "Wolverhampton", Nationality = "Gabon",     DateOfBirth = new DateTime(1993, 9, 1),   MarketValue = 22.0,  Goals = 2,  Assists = 2,  CleanSheets = 0,  TotalPoints = 85 },
                new Player { Id = 160, FirstName = "Andre",     LastName = "Trindade",     Position = Position.Midfielder, Club = "Wolverhampton", Nationality = "Brazil",    DateOfBirth = new DateTime(2001, 7, 16),  MarketValue = 28.0,  Goals = 1,  Assists = 2,  CleanSheets = 0,  TotalPoints = 88 },
                new Player { Id = 161, FirstName = "Tommy",     LastName = "Doyle",        Position = Position.Midfielder, Club = "Wolverhampton", Nationality = "England",   DateOfBirth = new DateTime(2001, 10, 17), MarketValue = 15.0,  Goals = 2,  Assists = 3,  CleanSheets = 0,  TotalPoints = 78 },
                new Player { Id = 162, FirstName = "Pablo",     LastName = "Sarabia",      Position = Position.Midfielder, Club = "Wolverhampton", Nationality = "Spain",     DateOfBirth = new DateTime(1992, 5, 11),  MarketValue = 18.0,  Goals = 5,  Assists = 5,  CleanSheets = 0,  TotalPoints = 105 },
                new Player { Id = 163, FirstName = "Jorgen",    LastName = "Strand Larsen", Position = Position.Forward,   Club = "Wolverhampton", Nationality = "Norway",    DateOfBirth = new DateTime(2000, 2, 6),   MarketValue = 35.0,  Goals = 12, Assists = 3,  CleanSheets = 0,  TotalPoints = 138 },
                new Player { Id = 164, FirstName = "Hwang",     LastName = "Hee-chan",     Position = Position.Forward,    Club = "Wolverhampton", Nationality = "South Korea", DateOfBirth = new DateTime(1996, 1, 26), MarketValue = 28.0,  Goals = 6,  Assists = 4,  CleanSheets = 0,  TotalPoints = 105 },
                new Player { Id = 165, FirstName = "Goncalo",   LastName = "Guedes",       Position = Position.Forward,    Club = "Wolverhampton", Nationality = "Portugal",  DateOfBirth = new DateTime(1996, 11, 29), MarketValue = 20.0,  Goals = 4,  Assists = 3,  CleanSheets = 0,  TotalPoints = 85 },

                // ==========================================
                // CRYSTAL PALACE (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 166, FirstName = "Dean",      LastName = "Henderson",    Position = Position.Goalkeeper, Club = "Crystal Palace", Nationality = "England",  DateOfBirth = new DateTime(1997, 3, 12),  MarketValue = 22.0,  Goals = 0,  Assists = 0,  CleanSheets = 9,  TotalPoints = 122 },
                new Player { Id = 167, FirstName = "Remi",      LastName = "Matthews",     Position = Position.Goalkeeper, Club = "Crystal Palace", Nationality = "England",  DateOfBirth = new DateTime(1994, 2, 10),  MarketValue = 3.0,   Goals = 0,  Assists = 0,  CleanSheets = 1,  TotalPoints = 22 },
                new Player { Id = 168, FirstName = "Marc",      LastName = "Guehi",        Position = Position.Defender,   Club = "Crystal Palace", Nationality = "England",  DateOfBirth = new DateTime(2000, 7, 13),  MarketValue = 45.0,  Goals = 2,  Assists = 1,  CleanSheets = 9,  TotalPoints = 128 },
                new Player { Id = 169, FirstName = "Maxence",   LastName = "Lacroix",      Position = Position.Defender,   Club = "Crystal Palace", Nationality = "France",   DateOfBirth = new DateTime(2000, 4, 6),   MarketValue = 30.0,  Goals = 2,  Assists = 1,  CleanSheets = 8,  TotalPoints = 110 },
                new Player { Id = 170, FirstName = "Tyrick",    LastName = "Mitchell",     Position = Position.Defender,   Club = "Crystal Palace", Nationality = "England",  DateOfBirth = new DateTime(1999, 9, 1),   MarketValue = 28.0,  Goals = 1,  Assists = 4,  CleanSheets = 8,  TotalPoints = 112 },
                new Player { Id = 171, FirstName = "Daniel",    LastName = "Munoz",        Position = Position.Defender,   Club = "Crystal Palace", Nationality = "Colombia", DateOfBirth = new DateTime(1996, 5, 26),  MarketValue = 32.0,  Goals = 3,  Assists = 5,  CleanSheets = 8,  TotalPoints = 128 },
                new Player { Id = 172, FirstName = "Chris",     LastName = "Richards",     Position = Position.Defender,   Club = "Crystal Palace", Nationality = "United States", DateOfBirth = new DateTime(2000, 3, 28), MarketValue = 22.0,  Goals = 2,  Assists = 0,  CleanSheets = 7,  TotalPoints = 92 },
                new Player { Id = 173, FirstName = "Eberechi",  LastName = "Eze",          Position = Position.Midfielder, Club = "Crystal Palace", Nationality = "England",  DateOfBirth = new DateTime(1998, 6, 29),  MarketValue = 55.0,  Goals = 11, Assists = 7,  CleanSheets = 0,  TotalPoints = 165 },
                new Player { Id = 174, FirstName = "Adam",      LastName = "Wharton",      Position = Position.Midfielder, Club = "Crystal Palace", Nationality = "England",  DateOfBirth = new DateTime(2004, 2, 6),   MarketValue = 40.0,  Goals = 1,  Assists = 5,  CleanSheets = 0,  TotalPoints = 108 },
                new Player { Id = 175, FirstName = "Will",      LastName = "Hughes",       Position = Position.Midfielder, Club = "Crystal Palace", Nationality = "England",  DateOfBirth = new DateTime(1995, 4, 17),  MarketValue = 15.0,  Goals = 1,  Assists = 3,  CleanSheets = 0,  TotalPoints = 78 },
                new Player { Id = 176, FirstName = "Jefferson", LastName = "Lerma",        Position = Position.Midfielder, Club = "Crystal Palace", Nationality = "Colombia", DateOfBirth = new DateTime(1994, 10, 25), MarketValue = 18.0,  Goals = 2,  Assists = 2,  CleanSheets = 0,  TotalPoints = 82 },
                new Player { Id = 177, FirstName = "Daichi",    LastName = "Kamada",       Position = Position.Midfielder, Club = "Crystal Palace", Nationality = "Japan",    DateOfBirth = new DateTime(1996, 8, 5),   MarketValue = 22.0,  Goals = 4,  Assists = 4,  CleanSheets = 0,  TotalPoints = 98 },
                new Player { Id = 178, FirstName = "Jean-Philippe", LastName = "Mateta",   Position = Position.Forward,    Club = "Crystal Palace", Nationality = "France",   DateOfBirth = new DateTime(1997, 6, 28),  MarketValue = 48.0,  Goals = 15, Assists = 4,  CleanSheets = 0,  TotalPoints = 168 },
                new Player { Id = 179, FirstName = "Ismaila",   LastName = "Sarr",         Position = Position.Forward,    Club = "Crystal Palace", Nationality = "Senegal",  DateOfBirth = new DateTime(1998, 2, 25),  MarketValue = 35.0,  Goals = 9,  Assists = 6,  CleanSheets = 0,  TotalPoints = 135 },
                new Player { Id = 180, FirstName = "Odsonne",   LastName = "Edouard",      Position = Position.Forward,    Club = "Crystal Palace", Nationality = "France",   DateOfBirth = new DateTime(1998, 1, 16),  MarketValue = 18.0,  Goals = 4,  Assists = 2,  CleanSheets = 0,  TotalPoints = 78 },

                // ==========================================
                // FULHAM (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 181, FirstName = "Bernd",     LastName = "Leno",         Position = Position.Goalkeeper, Club = "Fulham", Nationality = "Germany",        DateOfBirth = new DateTime(1992, 3, 4),   MarketValue = 20.0,  Goals = 0,  Assists = 0,  CleanSheets = 9,  TotalPoints = 122 },
                new Player { Id = 182, FirstName = "Steven",    LastName = "Benda",        Position = Position.Goalkeeper, Club = "Fulham", Nationality = "Germany",        DateOfBirth = new DateTime(1998, 10, 1),  MarketValue = 3.0,   Goals = 0,  Assists = 0,  CleanSheets = 1,  TotalPoints = 20 },
                new Player { Id = 183, FirstName = "Calvin",    LastName = "Bassey",       Position = Position.Defender,   Club = "Fulham", Nationality = "Nigeria",        DateOfBirth = new DateTime(1999, 12, 31), MarketValue = 28.0,  Goals = 1,  Assists = 1,  CleanSheets = 8,  TotalPoints = 105 },
                new Player { Id = 184, FirstName = "Joachim",   LastName = "Andersen",     Position = Position.Defender,   Club = "Fulham", Nationality = "Denmark",        DateOfBirth = new DateTime(1996, 5, 31),  MarketValue = 25.0,  Goals = 1,  Assists = 2,  CleanSheets = 8,  TotalPoints = 102 },
                new Player { Id = 185, FirstName = "Antonee",   LastName = "Robinson",     Position = Position.Defender,   Club = "Fulham", Nationality = "United States",  DateOfBirth = new DateTime(1997, 8, 8),   MarketValue = 35.0,  Goals = 2,  Assists = 7,  CleanSheets = 8,  TotalPoints = 130 },
                new Player { Id = 186, FirstName = "Kenny",     LastName = "Tete",         Position = Position.Defender,   Club = "Fulham", Nationality = "Netherlands",    DateOfBirth = new DateTime(1995, 10, 9),  MarketValue = 18.0,  Goals = 1,  Assists = 2,  CleanSheets = 6,  TotalPoints = 88 },
                new Player { Id = 187, FirstName = "Issa",      LastName = "Diop",         Position = Position.Defender,   Club = "Fulham", Nationality = "France",         DateOfBirth = new DateTime(1997, 1, 9),   MarketValue = 15.0,  Goals = 1,  Assists = 0,  CleanSheets = 6,  TotalPoints = 75 },
                new Player { Id = 188, FirstName = "Andreas",   LastName = "Pereira",      Position = Position.Midfielder, Club = "Fulham", Nationality = "Brazil",         DateOfBirth = new DateTime(1996, 1, 1),   MarketValue = 32.0,  Goals = 6,  Assists = 6,  CleanSheets = 0,  TotalPoints = 128 },
                new Player { Id = 189, FirstName = "Sasa",      LastName = "Lukic",        Position = Position.Midfielder, Club = "Fulham", Nationality = "Serbia",         DateOfBirth = new DateTime(1996, 8, 13),  MarketValue = 20.0,  Goals = 2,  Assists = 2,  CleanSheets = 0,  TotalPoints = 85 },
                new Player { Id = 190, FirstName = "Harrison",  LastName = "Reed",         Position = Position.Midfielder, Club = "Fulham", Nationality = "England",        DateOfBirth = new DateTime(1995, 1, 27),  MarketValue = 15.0,  Goals = 1,  Assists = 1,  CleanSheets = 0,  TotalPoints = 72 },
                new Player { Id = 191, FirstName = "Emile",     LastName = "Smith Rowe",   Position = Position.Midfielder, Club = "Fulham", Nationality = "England",        DateOfBirth = new DateTime(2000, 7, 28),  MarketValue = 30.0,  Goals = 5,  Assists = 5,  CleanSheets = 0,  TotalPoints = 115 },
                new Player { Id = 192, FirstName = "Alex",      LastName = "Iwobi",        Position = Position.Midfielder, Club = "Fulham", Nationality = "Nigeria",        DateOfBirth = new DateTime(1996, 5, 3),   MarketValue = 35.0,  Goals = 8,  Assists = 7,  CleanSheets = 0,  TotalPoints = 142 },
                new Player { Id = 193, FirstName = "Raul",      LastName = "Jimenez",      Position = Position.Forward,    Club = "Fulham", Nationality = "Mexico",         DateOfBirth = new DateTime(1991, 5, 5),   MarketValue = 28.0,  Goals = 10, Assists = 4,  CleanSheets = 0,  TotalPoints = 128 },
                new Player { Id = 194, FirstName = "Rodrigo",   LastName = "Muniz",        Position = Position.Forward,    Club = "Fulham", Nationality = "Brazil",         DateOfBirth = new DateTime(2001, 5, 4),   MarketValue = 30.0,  Goals = 9,  Assists = 2,  CleanSheets = 0,  TotalPoints = 118 },
                new Player { Id = 195, FirstName = "Adama",     LastName = "Traore",       Position = Position.Forward,    Club = "Fulham", Nationality = "Spain",          DateOfBirth = new DateTime(1996, 1, 25),  MarketValue = 22.0,  Goals = 3,  Assists = 6,  CleanSheets = 0,  TotalPoints = 102 },

                // ==========================================
                // BRENTFORD (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 196, FirstName = "Mark",      LastName = "Flekken",      Position = Position.Goalkeeper, Club = "Brentford", Nationality = "Netherlands",  DateOfBirth = new DateTime(1993, 6, 13),  MarketValue = 15.0,  Goals = 0,  Assists = 1,  CleanSheets = 7,  TotalPoints = 108 },
                new Player { Id = 197, FirstName = "Hakon",     LastName = "Valdimarsson",  Position = Position.Goalkeeper, Club = "Brentford", Nationality = "Iceland",     DateOfBirth = new DateTime(2001, 12, 14), MarketValue = 4.0,   Goals = 0,  Assists = 0,  CleanSheets = 1,  TotalPoints = 22 },
                new Player { Id = 198, FirstName = "Nathan",    LastName = "Collins",      Position = Position.Defender,   Club = "Brentford", Nationality = "Ireland",      DateOfBirth = new DateTime(2001, 4, 30),  MarketValue = 30.0,  Goals = 2,  Assists = 1,  CleanSheets = 7,  TotalPoints = 105 },
                new Player { Id = 199, FirstName = "Ethan",     LastName = "Pinnock",      Position = Position.Defender,   Club = "Brentford", Nationality = "Jamaica",      DateOfBirth = new DateTime(1993, 5, 29),  MarketValue = 18.0,  Goals = 2,  Assists = 0,  CleanSheets = 7,  TotalPoints = 90 },
                new Player { Id = 200, FirstName = "Kristoffer", LastName = "Ajer",        Position = Position.Defender,   Club = "Brentford", Nationality = "Norway",       DateOfBirth = new DateTime(1998, 4, 17),  MarketValue = 18.0,  Goals = 1,  Assists = 2,  CleanSheets = 6,  TotalPoints = 88 },
                new Player { Id = 201, FirstName = "Rico",      LastName = "Henry",        Position = Position.Defender,   Club = "Brentford", Nationality = "England",      DateOfBirth = new DateTime(1997, 7, 8),   MarketValue = 15.0,  Goals = 0,  Assists = 3,  CleanSheets = 6,  TotalPoints = 82 },
                new Player { Id = 202, FirstName = "Sepp",      LastName = "van den Berg",  Position = Position.Defender,  Club = "Brentford", Nationality = "Netherlands",  DateOfBirth = new DateTime(2001, 12, 20), MarketValue = 16.0,  Goals = 1,  Assists = 1,  CleanSheets = 6,  TotalPoints = 80 },
                new Player { Id = 203, FirstName = "Mathias",   LastName = "Jensen",       Position = Position.Midfielder, Club = "Brentford", Nationality = "Denmark",      DateOfBirth = new DateTime(1996, 1, 1),   MarketValue = 22.0,  Goals = 3,  Assists = 5,  CleanSheets = 0,  TotalPoints = 108 },
                new Player { Id = 204, FirstName = "Vitaly",    LastName = "Janelt",       Position = Position.Midfielder, Club = "Brentford", Nationality = "Germany",      DateOfBirth = new DateTime(1998, 5, 10),  MarketValue = 18.0,  Goals = 2,  Assists = 2,  CleanSheets = 0,  TotalPoints = 85 },
                new Player { Id = 205, FirstName = "Mikkel",    LastName = "Damsgaard",    Position = Position.Midfielder, Club = "Brentford", Nationality = "Denmark",      DateOfBirth = new DateTime(2000, 7, 3),   MarketValue = 28.0,  Goals = 4,  Assists = 8,  CleanSheets = 0,  TotalPoints = 128 },
                new Player { Id = 206, FirstName = "Yehor",     LastName = "Yarmolyuk",    Position = Position.Midfielder, Club = "Brentford", Nationality = "Ukraine",      DateOfBirth = new DateTime(2004, 3, 1),   MarketValue = 18.0,  Goals = 1,  Assists = 2,  CleanSheets = 0,  TotalPoints = 78 },
                new Player { Id = 207, FirstName = "Kevin",     LastName = "Schade",       Position = Position.Midfielder, Club = "Brentford", Nationality = "Germany",      DateOfBirth = new DateTime(2001, 11, 27), MarketValue = 25.0,  Goals = 7,  Assists = 4,  CleanSheets = 0,  TotalPoints = 115 },
                new Player { Id = 208, FirstName = "Yoane",     LastName = "Wissa",        Position = Position.Forward,    Club = "Brentford", Nationality = "DR Congo",     DateOfBirth = new DateTime(1996, 9, 3),   MarketValue = 42.0,  Goals = 16, Assists = 4,  CleanSheets = 0,  TotalPoints = 162 },
                new Player { Id = 209, FirstName = "Igor",      LastName = "Thiago",       Position = Position.Forward,    Club = "Brentford", Nationality = "Brazil",       DateOfBirth = new DateTime(2001, 6, 26),  MarketValue = 28.0,  Goals = 8,  Assists = 2,  CleanSheets = 0,  TotalPoints = 108 },
                new Player { Id = 210, FirstName = "Fabio",     LastName = "Carvalho",     Position = Position.Forward,    Club = "Brentford", Nationality = "Portugal",     DateOfBirth = new DateTime(2002, 8, 30),  MarketValue = 22.0,  Goals = 5,  Assists = 3,  CleanSheets = 0,  TotalPoints = 95 },

                // ==========================================
                // BOURNEMOUTH (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 211, FirstName = "Kepa",      LastName = "Arrizabalaga", Position = Position.Goalkeeper, Club = "Bournemouth", Nationality = "Spain",      DateOfBirth = new DateTime(1994, 10, 3),  MarketValue = 18.0,  Goals = 0,  Assists = 0,  CleanSheets = 8,  TotalPoints = 112 },
                new Player { Id = 212, FirstName = "Mark",      LastName = "Travers",      Position = Position.Goalkeeper, Club = "Bournemouth", Nationality = "Ireland",    DateOfBirth = new DateTime(1999, 5, 18),  MarketValue = 4.0,   Goals = 0,  Assists = 0,  CleanSheets = 1,  TotalPoints = 22 },
                new Player { Id = 213, FirstName = "Illia",     LastName = "Zabarnyi",     Position = Position.Defender,   Club = "Bournemouth", Nationality = "Ukraine",    DateOfBirth = new DateTime(2002, 9, 1),   MarketValue = 35.0,  Goals = 1,  Assists = 1,  CleanSheets = 8,  TotalPoints = 112 },
                new Player { Id = 214, FirstName = "Marcos",    LastName = "Senesi",       Position = Position.Defender,   Club = "Bournemouth", Nationality = "Argentina",  DateOfBirth = new DateTime(1997, 5, 10),  MarketValue = 28.0,  Goals = 2,  Assists = 1,  CleanSheets = 8,  TotalPoints = 108 },
                new Player { Id = 215, FirstName = "Adam",      LastName = "Smith",        Position = Position.Defender,   Club = "Bournemouth", Nationality = "England",    DateOfBirth = new DateTime(1991, 4, 29),  MarketValue = 8.0,   Goals = 0,  Assists = 2,  CleanSheets = 6,  TotalPoints = 72 },
                new Player { Id = 216, FirstName = "Chris",     LastName = "Mepham",       Position = Position.Defender,   Club = "Bournemouth", Nationality = "Wales",      DateOfBirth = new DateTime(1997, 11, 5),  MarketValue = 10.0,  Goals = 1,  Assists = 0,  CleanSheets = 5,  TotalPoints = 68 },
                new Player { Id = 217, FirstName = "Julio",     LastName = "Soler",        Position = Position.Defender,   Club = "Bournemouth", Nationality = "Argentina",  DateOfBirth = new DateTime(2005, 4, 16),  MarketValue = 12.0,  Goals = 0,  Assists = 1,  CleanSheets = 5,  TotalPoints = 62 },
                new Player { Id = 218, FirstName = "Ryan",      LastName = "Christie",     Position = Position.Midfielder, Club = "Bournemouth", Nationality = "Scotland",   DateOfBirth = new DateTime(1995, 2, 22),  MarketValue = 20.0,  Goals = 3,  Assists = 4,  CleanSheets = 0,  TotalPoints = 102 },
                new Player { Id = 219, FirstName = "Lewis",     LastName = "Cook",         Position = Position.Midfielder, Club = "Bournemouth", Nationality = "England",    DateOfBirth = new DateTime(1997, 2, 3),   MarketValue = 22.0,  Goals = 2,  Assists = 3,  CleanSheets = 0,  TotalPoints = 95 },
                new Player { Id = 220, FirstName = "Tyler",     LastName = "Adams",        Position = Position.Midfielder, Club = "Bournemouth", Nationality = "United States", DateOfBirth = new DateTime(1999, 2, 14), MarketValue = 25.0, Goals = 2, Assists = 2,  CleanSheets = 0,  TotalPoints = 92 },
                new Player { Id = 221, FirstName = "Marcus",    LastName = "Tavernier",    Position = Position.Midfielder, Club = "Bournemouth", Nationality = "England",    DateOfBirth = new DateTime(1999, 3, 22),  MarketValue = 24.0,  Goals = 4,  Assists = 5,  CleanSheets = 0,  TotalPoints = 110 },
                new Player { Id = 222, FirstName = "Alex",      LastName = "Scott",        Position = Position.Midfielder, Club = "Bournemouth", Nationality = "England",    DateOfBirth = new DateTime(2003, 8, 21),  MarketValue = 22.0,  Goals = 2,  Assists = 3,  CleanSheets = 0,  TotalPoints = 88 },
                new Player { Id = 223, FirstName = "Antoine",   LastName = "Semenyo",      Position = Position.Forward,    Club = "Bournemouth", Nationality = "Ghana",      DateOfBirth = new DateTime(2000, 1, 7),   MarketValue = 45.0,  Goals = 13, Assists = 6,  CleanSheets = 0,  TotalPoints = 162 },
                new Player { Id = 224, FirstName = "Justin",    LastName = "Kluivert",     Position = Position.Forward,    Club = "Bournemouth", Nationality = "Netherlands", DateOfBirth = new DateTime(1999, 5, 5),   MarketValue = 35.0,  Goals = 11, Assists = 5,  CleanSheets = 0,  TotalPoints = 142 },
                new Player { Id = 225, FirstName = "Evanilson", LastName = "de Lima",      Position = Position.Forward,    Club = "Bournemouth", Nationality = "Brazil",     DateOfBirth = new DateTime(1999, 10, 6),  MarketValue = 38.0,  Goals = 10, Assists = 3,  CleanSheets = 0,  TotalPoints = 128 },

                // ==========================================
                // EVERTON (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 226, FirstName = "Jordan",    LastName = "Pickford",     Position = Position.Goalkeeper, Club = "Everton", Nationality = "England",        DateOfBirth = new DateTime(1994, 3, 7),   MarketValue = 28.0,  Goals = 0,  Assists = 1,  CleanSheets = 11, TotalPoints = 145 },
                new Player { Id = 227, FirstName = "Joao",      LastName = "Virginia",     Position = Position.Goalkeeper, Club = "Everton", Nationality = "Portugal",       DateOfBirth = new DateTime(1999, 10, 10), MarketValue = 3.0,   Goals = 0,  Assists = 0,  CleanSheets = 1,  TotalPoints = 20 },
                new Player { Id = 228, FirstName = "James",     LastName = "Tarkowski",    Position = Position.Defender,   Club = "Everton", Nationality = "England",        DateOfBirth = new DateTime(1992, 11, 19), MarketValue = 22.0,  Goals = 2,  Assists = 1,  CleanSheets = 10, TotalPoints = 115 },
                new Player { Id = 229, FirstName = "Jarrad",    LastName = "Branthwaite",  Position = Position.Defender,   Club = "Everton", Nationality = "England",        DateOfBirth = new DateTime(2002, 6, 27),  MarketValue = 40.0,  Goals = 2,  Assists = 1,  CleanSheets = 10, TotalPoints = 122 },
                new Player { Id = 230, FirstName = "Vitalii",   LastName = "Mykolenko",    Position = Position.Defender,   Club = "Everton", Nationality = "Ukraine",        DateOfBirth = new DateTime(1999, 5, 29),  MarketValue = 20.0,  Goals = 1,  Assists = 2,  CleanSheets = 9,  TotalPoints = 102 },
                new Player { Id = 231, FirstName = "Seamus",    LastName = "Coleman",      Position = Position.Defender,   Club = "Everton", Nationality = "Ireland",        DateOfBirth = new DateTime(1988, 10, 11), MarketValue = 4.0,   Goals = 0,  Assists = 1,  CleanSheets = 5,  TotalPoints = 52 },
                new Player { Id = 232, FirstName = "Michael",   LastName = "Keane",        Position = Position.Defender,   Club = "Everton", Nationality = "England",        DateOfBirth = new DateTime(1993, 1, 11),  MarketValue = 10.0,  Goals = 1,  Assists = 0,  CleanSheets = 6,  TotalPoints = 70 },
                new Player { Id = 233, FirstName = "Idrissa",   LastName = "Gueye",        Position = Position.Midfielder, Club = "Everton", Nationality = "Senegal",        DateOfBirth = new DateTime(1989, 9, 26),  MarketValue = 15.0,  Goals = 2,  Assists = 2,  CleanSheets = 0,  TotalPoints = 88 },
                new Player { Id = 234, FirstName = "James",     LastName = "Garner",       Position = Position.Midfielder, Club = "Everton", Nationality = "England",        DateOfBirth = new DateTime(2001, 3, 13),  MarketValue = 22.0,  Goals = 2,  Assists = 4,  CleanSheets = 0,  TotalPoints = 95 },
                new Player { Id = 235, FirstName = "Abdoulaye", LastName = "Doucoure",     Position = Position.Midfielder, Club = "Everton", Nationality = "Mali",           DateOfBirth = new DateTime(1993, 1, 1),   MarketValue = 20.0,  Goals = 6,  Assists = 3,  CleanSheets = 0,  TotalPoints = 112 },
                new Player { Id = 236, FirstName = "Dwight",    LastName = "McNeil",       Position = Position.Midfielder, Club = "Everton", Nationality = "England",        DateOfBirth = new DateTime(1999, 11, 22), MarketValue = 25.0,  Goals = 5,  Assists = 5,  CleanSheets = 0,  TotalPoints = 115 },
                new Player { Id = 237, FirstName = "Jack",      LastName = "Harrison",     Position = Position.Midfielder, Club = "Everton", Nationality = "England",        DateOfBirth = new DateTime(1996, 11, 20), MarketValue = 18.0,  Goals = 3,  Assists = 4,  CleanSheets = 0,  TotalPoints = 92 },
                new Player { Id = 238, FirstName = "Beto",      LastName = "Betuncal",     Position = Position.Forward,    Club = "Everton", Nationality = "Portugal",       DateOfBirth = new DateTime(1998, 1, 31),  MarketValue = 28.0,  Goals = 9,  Assists = 2,  CleanSheets = 0,  TotalPoints = 112 },
                new Player { Id = 239, FirstName = "Iliman",    LastName = "Ndiaye",       Position = Position.Forward,    Club = "Everton", Nationality = "Senegal",        DateOfBirth = new DateTime(2000, 3, 6),   MarketValue = 32.0,  Goals = 8,  Assists = 5,  CleanSheets = 0,  TotalPoints = 122 },
                new Player { Id = 240, FirstName = "Youssef",   LastName = "Chermiti",     Position = Position.Forward,    Club = "Everton", Nationality = "Portugal",       DateOfBirth = new DateTime(2004, 5, 24),  MarketValue = 15.0,  Goals = 3,  Assists = 1,  CleanSheets = 0,  TotalPoints = 68 },

                // ==========================================
                // NOTTINGHAM FOREST (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 241, FirstName = "Matz",      LastName = "Sels",         Position = Position.Goalkeeper, Club = "Nottingham Forest", Nationality = "Belgium", DateOfBirth = new DateTime(1992, 2, 26),  MarketValue = 22.0,  Goals = 0,  Assists = 0,  CleanSheets = 13, TotalPoints = 148 },
                new Player { Id = 242, FirstName = "Carlos",    LastName = "Miguel",       Position = Position.Goalkeeper, Club = "Nottingham Forest", Nationality = "Brazil",  DateOfBirth = new DateTime(1998, 8, 26),  MarketValue = 6.0,   Goals = 0,  Assists = 0,  CleanSheets = 2,  TotalPoints = 30 },
                new Player { Id = 243, FirstName = "Murillo",   LastName = "Costa",        Position = Position.Defender,   Club = "Nottingham Forest", Nationality = "Brazil",  DateOfBirth = new DateTime(2002, 4, 11),  MarketValue = 38.0,  Goals = 2,  Assists = 2,  CleanSheets = 11, TotalPoints = 130 },
                new Player { Id = 244, FirstName = "Nikola",    LastName = "Milenkovic",   Position = Position.Defender,   Club = "Nottingham Forest", Nationality = "Serbia",  DateOfBirth = new DateTime(1997, 10, 12), MarketValue = 30.0,  Goals = 4,  Assists = 1,  CleanSheets = 11, TotalPoints = 132 },
                new Player { Id = 245, FirstName = "Neco",      LastName = "Williams",     Position = Position.Defender,   Club = "Nottingham Forest", Nationality = "Wales",   DateOfBirth = new DateTime(2001, 4, 13),  MarketValue = 22.0,  Goals = 2,  Assists = 4,  CleanSheets = 9,  TotalPoints = 118 },
                new Player { Id = 246, FirstName = "Ola",       LastName = "Aina",         Position = Position.Defender,   Club = "Nottingham Forest", Nationality = "Nigeria", DateOfBirth = new DateTime(1996, 10, 8),  MarketValue = 24.0,  Goals = 1,  Assists = 2,  CleanSheets = 10, TotalPoints = 115 },
                new Player { Id = 247, FirstName = "Morato",    LastName = "Silva",        Position = Position.Defender,   Club = "Nottingham Forest", Nationality = "Brazil",  DateOfBirth = new DateTime(2001, 4, 16),  MarketValue = 14.0,  Goals = 0,  Assists = 0,  CleanSheets = 6,  TotalPoints = 68 },
                new Player { Id = 248, FirstName = "Morgan",    LastName = "Gibbs-White",  Position = Position.Midfielder, Club = "Nottingham Forest", Nationality = "England", DateOfBirth = new DateTime(2000, 1, 27),  MarketValue = 48.0,  Goals = 8,  Assists = 9,  CleanSheets = 0,  TotalPoints = 158 },
                new Player { Id = 249, FirstName = "Elliot",    LastName = "Anderson",     Position = Position.Midfielder, Club = "Nottingham Forest", Nationality = "England", DateOfBirth = new DateTime(2002, 11, 6),  MarketValue = 35.0,  Goals = 3,  Assists = 5,  CleanSheets = 0,  TotalPoints = 118 },
                new Player { Id = 250, FirstName = "Ryan",      LastName = "Yates",        Position = Position.Midfielder, Club = "Nottingham Forest", Nationality = "England", DateOfBirth = new DateTime(1997, 11, 21), MarketValue = 18.0,  Goals = 2,  Assists = 2,  CleanSheets = 0,  TotalPoints = 82 },
                new Player { Id = 251, FirstName = "Nicolas",   LastName = "Dominguez",    Position = Position.Midfielder, Club = "Nottingham Forest", Nationality = "Argentina", DateOfBirth = new DateTime(1998, 6, 28), MarketValue = 20.0, Goals = 3, Assists = 2,  CleanSheets = 0,  TotalPoints = 88 },
                new Player { Id = 252, FirstName = "Callum",    LastName = "Hudson-Odoi",  Position = Position.Midfielder, Club = "Nottingham Forest", Nationality = "England", DateOfBirth = new DateTime(2000, 11, 7),  MarketValue = 28.0,  Goals = 6,  Assists = 4,  CleanSheets = 0,  TotalPoints = 118 },
                new Player { Id = 253, FirstName = "Chris",     LastName = "Wood",         Position = Position.Forward,    Club = "Nottingham Forest", Nationality = "New Zealand", DateOfBirth = new DateTime(1991, 12, 7), MarketValue = 42.0, Goals = 18, Assists = 3,  CleanSheets = 0,  TotalPoints = 175 },
                new Player { Id = 254, FirstName = "Taiwo",     LastName = "Awoniyi",      Position = Position.Forward,    Club = "Nottingham Forest", Nationality = "Nigeria", DateOfBirth = new DateTime(1997, 8, 12),  MarketValue = 25.0,  Goals = 6,  Assists = 2,  CleanSheets = 0,  TotalPoints = 95 },
                new Player { Id = 255, FirstName = "Ramon",     LastName = "Sosa",         Position = Position.Forward,    Club = "Nottingham Forest", Nationality = "Paraguay", DateOfBirth = new DateTime(2001, 8, 28), MarketValue = 20.0,  Goals = 4,  Assists = 3,  CleanSheets = 0,  TotalPoints = 82 },

                // ==========================================
                // LEEDS UNITED (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 256, FirstName = "Illan",     LastName = "Meslier",      Position = Position.Goalkeeper, Club = "Leeds United", Nationality = "France",     DateOfBirth = new DateTime(2000, 3, 2),   MarketValue = 15.0,  Goals = 0,  Assists = 0,  CleanSheets = 7,  TotalPoints = 102 },
                new Player { Id = 257, FirstName = "Lucas",     LastName = "Perri",        Position = Position.Goalkeeper, Club = "Leeds United", Nationality = "Brazil",     DateOfBirth = new DateTime(1997, 12, 10), MarketValue = 8.0,   Goals = 0,  Assists = 0,  CleanSheets = 3,  TotalPoints = 48 },
                new Player { Id = 258, FirstName = "Pascal",    LastName = "Struijk",      Position = Position.Defender,   Club = "Leeds United", Nationality = "Netherlands", DateOfBirth = new DateTime(1999, 8, 11), MarketValue = 18.0,  Goals = 2,  Assists = 1,  CleanSheets = 7,  TotalPoints = 92 },
                new Player { Id = 259, FirstName = "Joe",       LastName = "Rodon",        Position = Position.Defender,   Club = "Leeds United", Nationality = "Wales",      DateOfBirth = new DateTime(1997, 10, 22), MarketValue = 16.0,  Goals = 1,  Assists = 0,  CleanSheets = 7,  TotalPoints = 82 },
                new Player { Id = 260, FirstName = "Jayden",    LastName = "Bogle",        Position = Position.Defender,   Club = "Leeds United", Nationality = "England",    DateOfBirth = new DateTime(2000, 7, 27),  MarketValue = 15.0,  Goals = 1,  Assists = 3,  CleanSheets = 6,  TotalPoints = 85 },
                new Player { Id = 261, FirstName = "Junior",    LastName = "Firpo",        Position = Position.Defender,   Club = "Leeds United", Nationality = "Dominican Republic", DateOfBirth = new DateTime(1996, 8, 22), MarketValue = 12.0, Goals = 1, Assists = 3, CleanSheets = 6, TotalPoints = 80 },
                new Player { Id = 262, FirstName = "Max",       LastName = "Wober",        Position = Position.Defender,   Club = "Leeds United", Nationality = "Austria",    DateOfBirth = new DateTime(1998, 2, 16),  MarketValue = 12.0,  Goals = 0,  Assists = 1,  CleanSheets = 5,  TotalPoints = 65 },
                new Player { Id = 263, FirstName = "Ethan",     LastName = "Ampadu",       Position = Position.Midfielder, Club = "Leeds United", Nationality = "Wales",      DateOfBirth = new DateTime(2000, 9, 14),  MarketValue = 22.0,  Goals = 1,  Assists = 2,  CleanSheets = 0,  TotalPoints = 88 },
                new Player { Id = 264, FirstName = "Ilia",      LastName = "Gruev",        Position = Position.Midfielder, Club = "Leeds United", Nationality = "Bulgaria",   DateOfBirth = new DateTime(2000, 5, 6),   MarketValue = 14.0,  Goals = 1,  Assists = 2,  CleanSheets = 0,  TotalPoints = 72 },
                new Player { Id = 265, FirstName = "Brenden",   LastName = "Aaronson",     Position = Position.Midfielder, Club = "Leeds United", Nationality = "United States", DateOfBirth = new DateTime(2000, 10, 22), MarketValue = 20.0, Goals = 5, Assists = 5, CleanSheets = 0, TotalPoints = 112 },
                new Player { Id = 266, FirstName = "Daniel",    LastName = "James",        Position = Position.Midfielder, Club = "Leeds United", Nationality = "Wales",      DateOfBirth = new DateTime(1997, 11, 10), MarketValue = 22.0,  Goals = 6,  Assists = 6,  CleanSheets = 0,  TotalPoints = 118 },
                new Player { Id = 267, FirstName = "Anton",     LastName = "Stach",        Position = Position.Midfielder, Club = "Leeds United", Nationality = "Germany",    DateOfBirth = new DateTime(1998, 11, 15), MarketValue = 16.0,  Goals = 2,  Assists = 2,  CleanSheets = 0,  TotalPoints = 78 },
                new Player { Id = 268, FirstName = "Joel",      LastName = "Piroe",        Position = Position.Forward,    Club = "Leeds United", Nationality = "Netherlands", DateOfBirth = new DateTime(1999, 8, 2),   MarketValue = 28.0,  Goals = 12, Assists = 3,  CleanSheets = 0,  TotalPoints = 128 },
                new Player { Id = 269, FirstName = "Patrick",   LastName = "Bamford",      Position = Position.Forward,    Club = "Leeds United", Nationality = "England",    DateOfBirth = new DateTime(1993, 9, 5),   MarketValue = 12.0,  Goals = 5,  Assists = 2,  CleanSheets = 0,  TotalPoints = 78 },
                new Player { Id = 270, FirstName = "Largie",    LastName = "Ramazani",     Position = Position.Forward,    Club = "Leeds United", Nationality = "Belgium",    DateOfBirth = new DateTime(2001, 2, 27),  MarketValue = 15.0,  Goals = 4,  Assists = 3,  CleanSheets = 0,  TotalPoints = 78 },

                // ==========================================
                // BURNLEY (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 271, FirstName = "James",     LastName = "Trafford",     Position = Position.Goalkeeper, Club = "Burnley", Nationality = "England",        DateOfBirth = new DateTime(2002, 10, 10), MarketValue = 18.0,  Goals = 0,  Assists = 0,  CleanSheets = 12, TotalPoints = 138 },
                new Player { Id = 272, FirstName = "Vaclav",    LastName = "Hladky",       Position = Position.Goalkeeper, Club = "Burnley", Nationality = "Czech Republic", DateOfBirth = new DateTime(1990, 11, 14), MarketValue = 3.0,   Goals = 0,  Assists = 0,  CleanSheets = 2,  TotalPoints = 28 },
                new Player { Id = 273, FirstName = "Maxime",    LastName = "Esteve",       Position = Position.Defender,   Club = "Burnley", Nationality = "France",         DateOfBirth = new DateTime(2002, 6, 26),  MarketValue = 18.0,  Goals = 1,  Assists = 1,  CleanSheets = 10, TotalPoints = 102 },
                new Player { Id = 274, FirstName = "Dara",      LastName = "O'Shea",       Position = Position.Defender,   Club = "Burnley", Nationality = "Ireland",        DateOfBirth = new DateTime(1999, 3, 4),   MarketValue = 16.0,  Goals = 1,  Assists = 0,  CleanSheets = 10, TotalPoints = 95 },
                new Player { Id = 275, FirstName = "Connor",    LastName = "Roberts",      Position = Position.Defender,   Club = "Burnley", Nationality = "Wales",          DateOfBirth = new DateTime(1995, 9, 23),  MarketValue = 12.0,  Goals = 1,  Assists = 3,  CleanSheets = 9,  TotalPoints = 92 },
                new Player { Id = 276, FirstName = "CJ",        LastName = "Egan-Riley",   Position = Position.Defender,   Club = "Burnley", Nationality = "England",        DateOfBirth = new DateTime(2003, 1, 2),   MarketValue = 14.0,  Goals = 1,  Assists = 1,  CleanSheets = 9,  TotalPoints = 88 },
                new Player { Id = 277, FirstName = "Jordan",    LastName = "Beyer",        Position = Position.Defender,   Club = "Burnley", Nationality = "Germany",        DateOfBirth = new DateTime(2000, 5, 19),  MarketValue = 12.0,  Goals = 0,  Assists = 0,  CleanSheets = 8,  TotalPoints = 78 },
                new Player { Id = 278, FirstName = "Josh",      LastName = "Cullen",       Position = Position.Midfielder, Club = "Burnley", Nationality = "Ireland",        DateOfBirth = new DateTime(1996, 4, 7),   MarketValue = 15.0,  Goals = 2,  Assists = 3,  CleanSheets = 0,  TotalPoints = 88 },
                new Player { Id = 279, FirstName = "Josh",      LastName = "Brownhill",    Position = Position.Midfielder, Club = "Burnley", Nationality = "England",        DateOfBirth = new DateTime(1995, 12, 19), MarketValue = 16.0,  Goals = 5,  Assists = 4,  CleanSheets = 0,  TotalPoints = 108 },
                new Player { Id = 280, FirstName = "Hannibal",  LastName = "Mejbri",       Position = Position.Midfielder, Club = "Burnley", Nationality = "Tunisia",        DateOfBirth = new DateTime(2003, 1, 21),  MarketValue = 14.0,  Goals = 2,  Assists = 3,  CleanSheets = 0,  TotalPoints = 82 },
                new Player { Id = 281, FirstName = "Jacob",     LastName = "Bruun Larsen",  Position = Position.Midfielder, Club = "Burnley", Nationality = "Denmark",       DateOfBirth = new DateTime(1998, 9, 19),  MarketValue = 12.0,  Goals = 3,  Assists = 3,  CleanSheets = 0,  TotalPoints = 80 },
                new Player { Id = 282, FirstName = "Lesley",    LastName = "Ugochukwu",    Position = Position.Midfielder, Club = "Burnley", Nationality = "France",         DateOfBirth = new DateTime(2004, 3, 26),  MarketValue = 16.0,  Goals = 1,  Assists = 1,  CleanSheets = 0,  TotalPoints = 72 },
                new Player { Id = 283, FirstName = "Lyle",      LastName = "Foster",       Position = Position.Forward,    Club = "Burnley", Nationality = "South Africa",   DateOfBirth = new DateTime(2000, 9, 3),   MarketValue = 20.0,  Goals = 8,  Assists = 3,  CleanSheets = 0,  TotalPoints = 105 },
                new Player { Id = 284, FirstName = "Zian",      LastName = "Flemming",     Position = Position.Forward,    Club = "Burnley", Nationality = "Netherlands",    DateOfBirth = new DateTime(1998, 7, 17),  MarketValue = 16.0,  Goals = 6,  Assists = 4,  CleanSheets = 0,  TotalPoints = 95 },
                new Player { Id = 285, FirstName = "Jaidon",    LastName = "Anthony",      Position = Position.Forward,    Club = "Burnley", Nationality = "England",        DateOfBirth = new DateTime(1999, 12, 1),  MarketValue = 15.0,  Goals = 5,  Assists = 5,  CleanSheets = 0,  TotalPoints = 92 },

                // ==========================================
                // SUNDERLAND (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 286, FirstName = "Anthony",   LastName = "Patterson",    Position = Position.Goalkeeper, Club = "Sunderland", Nationality = "England",     DateOfBirth = new DateTime(2000, 5, 10),  MarketValue = 12.0,  Goals = 0,  Assists = 0,  CleanSheets = 9,  TotalPoints = 118 },
                new Player { Id = 287, FirstName = "Simon",     LastName = "Moore",        Position = Position.Goalkeeper, Club = "Sunderland", Nationality = "England",     DateOfBirth = new DateTime(1990, 5, 19),  MarketValue = 3.0,   Goals = 0,  Assists = 0,  CleanSheets = 1,  TotalPoints = 20 },
                new Player { Id = 288, FirstName = "Dan",       LastName = "Ballard",      Position = Position.Defender,   Club = "Sunderland", Nationality = "Northern Ireland", DateOfBirth = new DateTime(1999, 9, 22), MarketValue = 18.0, Goals = 2, Assists = 0, CleanSheets = 9, TotalPoints = 100 },
                new Player { Id = 289, FirstName = "Luke",      LastName = "O'Nien",       Position = Position.Defender,   Club = "Sunderland", Nationality = "England",     DateOfBirth = new DateTime(1994, 11, 21), MarketValue = 14.0,  Goals = 2,  Assists = 1,  CleanSheets = 8,  TotalPoints = 92 },
                new Player { Id = 290, FirstName = "Trai",      LastName = "Hume",         Position = Position.Defender,   Club = "Sunderland", Nationality = "Northern Ireland", DateOfBirth = new DateTime(2002, 4, 7), MarketValue = 16.0, Goals = 1, Assists = 3, CleanSheets = 8, TotalPoints = 95 },
                new Player { Id = 291, FirstName = "Dennis",    LastName = "Cirkin",       Position = Position.Defender,   Club = "Sunderland", Nationality = "England",     DateOfBirth = new DateTime(2002, 4, 6),   MarketValue = 12.0,  Goals = 1,  Assists = 2,  CleanSheets = 7,  TotalPoints = 82 },
                new Player { Id = 292, FirstName = "Leo",       LastName = "Hjelde",       Position = Position.Defender,   Club = "Sunderland", Nationality = "Norway",      DateOfBirth = new DateTime(2003, 8, 26),  MarketValue = 10.0,  Goals = 0,  Assists = 0,  CleanSheets = 6,  TotalPoints = 62 },
                new Player { Id = 293, FirstName = "Dan",       LastName = "Neil",         Position = Position.Midfielder, Club = "Sunderland", Nationality = "England",     DateOfBirth = new DateTime(2001, 12, 1),  MarketValue = 18.0,  Goals = 2,  Assists = 4,  CleanSheets = 0,  TotalPoints = 95 },
                new Player { Id = 294, FirstName = "Chris",     LastName = "Rigg",         Position = Position.Midfielder, Club = "Sunderland", Nationality = "England",     DateOfBirth = new DateTime(2007, 6, 1),   MarketValue = 20.0,  Goals = 4,  Assists = 3,  CleanSheets = 0,  TotalPoints = 98 },
                new Player { Id = 295, FirstName = "Romaine",   LastName = "Mundle",       Position = Position.Midfielder, Club = "Sunderland", Nationality = "England",     DateOfBirth = new DateTime(2003, 4, 15), MarketValue = 14.0, Goals = 3, Assists = 4, CleanSheets = 0, TotalPoints = 88 },
                new Player { Id = 296, FirstName = "Alan",      LastName = "Browne",       Position = Position.Midfielder, Club = "Sunderland", Nationality = "Ireland",     DateOfBirth = new DateTime(1995, 4, 15),  MarketValue = 12.0,  Goals = 2,  Assists = 2,  CleanSheets = 0,  TotalPoints = 78 },
                new Player { Id = 297, FirstName = "Patrick",   LastName = "Roberts",      Position = Position.Midfielder, Club = "Sunderland", Nationality = "England",     DateOfBirth = new DateTime(1997, 2, 5),   MarketValue = 14.0,  Goals = 3,  Assists = 5,  CleanSheets = 0,  TotalPoints = 92 },
                new Player { Id = 298, FirstName = "Wilson",    LastName = "Isidor",       Position = Position.Forward,    Club = "Sunderland", Nationality = "France",      DateOfBirth = new DateTime(2000, 8, 27),  MarketValue = 22.0,  Goals = 11, Assists = 3,  CleanSheets = 0,  TotalPoints = 122 },
                new Player { Id = 299, FirstName = "Eliezer",   LastName = "Mayenda",      Position = Position.Forward,    Club = "Sunderland", Nationality = "Spain",       DateOfBirth = new DateTime(2005, 5, 4),   MarketValue = 16.0,  Goals = 6,  Assists = 3,  CleanSheets = 0,  TotalPoints = 92 },
                new Player { Id = 300, FirstName = "Ahmed",     LastName = "Abdullahi",    Position = Position.Forward,    Club = "Sunderland", Nationality = "Nigeria",     DateOfBirth = new DateTime(2002, 1, 6),   MarketValue = 12.0,  Goals = 4,  Assists = 2,  CleanSheets = 0,  TotalPoints = 78 },
            };
        }

        public List<Player> GetAll() => _players;
        public Player? GetById(int id) => _players.FirstOrDefault(p => p.Id == id);
    }
}
