using FantasyFootball.Models;

namespace FantasyFootball.Repositories
{
    public class PlayerMockRepository
    {
        private readonly List<Player> _players;

        public PlayerMockRepository()
        {
            _players = new List<Player>
            {
                // ==========================================
                // MANCHESTER CITY (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 1,  FirstName = "Erling",   LastName = "Haaland",     Position = Position.Forward,    Club = "Manchester City", Nationality = "Norway",      DateOfBirth = new DateTime(2000, 7, 21), MarketValue = 180.0, Goals = 27, Assists = 5,  CleanSheets = 0,  TotalPoints = 275 },
                new Player { Id = 13, FirstName = "Josko",    LastName = "Gvardiol",    Position = Position.Defender,   Club = "Manchester City", Nationality = "Croatia",     DateOfBirth = new DateTime(2002, 1, 23), MarketValue = 75.0,  Goals = 5,  Assists = 4,  CleanSheets = 12, TotalPoints = 160 },
                new Player { Id = 16, FirstName = "Ederson",  LastName = "Moraes",      Position = Position.Goalkeeper, Club = "Manchester City", Nationality = "Brazil",      DateOfBirth = new DateTime(1993, 8, 17), MarketValue = 35.0,  Goals = 0,  Assists = 1,  CleanSheets = 14, TotalPoints = 152 },
                new Player { Id = 17, FirstName = "Stefan",   LastName = "Ortega",      Position = Position.Goalkeeper, Club = "Manchester City", Nationality = "Germany",     DateOfBirth = new DateTime(1992, 11, 6), MarketValue = 12.0,  Goals = 0,  Assists = 0,  CleanSheets = 6,  TotalPoints = 68 },
                new Player { Id = 18, FirstName = "Ruben",    LastName = "Dias",        Position = Position.Defender,   Club = "Manchester City", Nationality = "Portugal",    DateOfBirth = new DateTime(1997, 5, 14), MarketValue = 70.0,  Goals = 2,  Assists = 1,  CleanSheets = 13, TotalPoints = 155 },
                new Player { Id = 19, FirstName = "John",     LastName = "Stones",      Position = Position.Defender,   Club = "Manchester City", Nationality = "England",     DateOfBirth = new DateTime(1994, 5, 28), MarketValue = 40.0,  Goals = 1,  Assists = 2,  CleanSheets = 11, TotalPoints = 128 },
                new Player { Id = 20, FirstName = "Kyle",     LastName = "Walker",      Position = Position.Defender,   Club = "Manchester City", Nationality = "England",     DateOfBirth = new DateTime(1990, 5, 28), MarketValue = 18.0,  Goals = 0,  Assists = 3,  CleanSheets = 10, TotalPoints = 112 },
                new Player { Id = 21, FirstName = "Manuel",   LastName = "Akanji",      Position = Position.Defender,   Club = "Manchester City", Nationality = "Switzerland", DateOfBirth = new DateTime(1995, 7, 19), MarketValue = 35.0,  Goals = 1,  Assists = 1,  CleanSheets = 12, TotalPoints = 135 },
                new Player { Id = 22, FirstName = "Kevin",    LastName = "De Bruyne",   Position = Position.Midfielder, Club = "Manchester City", Nationality = "Belgium",     DateOfBirth = new DateTime(1991, 6, 28), MarketValue = 55.0,  Goals = 6,  Assists = 14, CleanSheets = 0,  TotalPoints = 198 },
                new Player { Id = 23, FirstName = "Phil",     LastName = "Foden",       Position = Position.Midfielder, Club = "Manchester City", Nationality = "England",     DateOfBirth = new DateTime(2000, 5, 28), MarketValue = 110.0, Goals = 12, Assists = 9,  CleanSheets = 0,  TotalPoints = 205 },
                new Player { Id = 24, FirstName = "Bernardo", LastName = "Silva",       Position = Position.Midfielder, Club = "Manchester City", Nationality = "Portugal",    DateOfBirth = new DateTime(1994, 8, 10), MarketValue = 65.0,  Goals = 5,  Assists = 10, CleanSheets = 0,  TotalPoints = 168 },
                new Player { Id = 25, FirstName = "Mateo",    LastName = "Kovacic",     Position = Position.Midfielder, Club = "Manchester City", Nationality = "Croatia",     DateOfBirth = new DateTime(1994, 5, 6),  MarketValue = 30.0,  Goals = 3,  Assists = 5,  CleanSheets = 0,  TotalPoints = 118 },
                new Player { Id = 26, FirstName = "Savinho",  LastName = "Trovoada",    Position = Position.Midfielder, Club = "Manchester City", Nationality = "Brazil",      DateOfBirth = new DateTime(2004, 4, 10), MarketValue = 55.0,  Goals = 7,  Assists = 8,  CleanSheets = 0,  TotalPoints = 155 },
                new Player { Id = 27, FirstName = "Jeremy",   LastName = "Doku",        Position = Position.Forward,    Club = "Manchester City", Nationality = "Belgium",     DateOfBirth = new DateTime(2002, 5, 27), MarketValue = 65.0,  Goals = 8,  Assists = 7,  CleanSheets = 0,  TotalPoints = 148 },
                new Player { Id = 28, FirstName = "Oscar",    LastName = "Bobb",        Position = Position.Forward,    Club = "Manchester City", Nationality = "Norway",      DateOfBirth = new DateTime(2003, 7, 12), MarketValue = 30.0,  Goals = 6,  Assists = 4,  CleanSheets = 0,  TotalPoints = 112 },

                // ==========================================
                // LIVERPOOL (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 5,  FirstName = "Alisson",    LastName = "Becker",          Position = Position.Goalkeeper, Club = "Liverpool", Nationality = "Brazil",      DateOfBirth = new DateTime(1992, 10, 2),  MarketValue = 40.0,  Goals = 0,  Assists = 0,  CleanSheets = 16, TotalPoints = 165 },
                new Player { Id = 29, FirstName = "Caoimhin",   LastName = "Kelleher",        Position = Position.Goalkeeper, Club = "Liverpool", Nationality = "Ireland",     DateOfBirth = new DateTime(1998, 11, 23), MarketValue = 15.0,  Goals = 0,  Assists = 0,  CleanSheets = 5,  TotalPoints = 58 },
                new Player { Id = 4,  FirstName = "Virgil",     LastName = "van Dijk",        Position = Position.Defender,   Club = "Liverpool", Nationality = "Netherlands", DateOfBirth = new DateTime(1991, 7, 8),   MarketValue = 45.0,  Goals = 3,  Assists = 1,  CleanSheets = 15, TotalPoints = 180 },
                new Player { Id = 30, FirstName = "Trent",      LastName = "Alexander-Arnold", Position = Position.Defender,   Club = "Liverpool", Nationality = "England",    DateOfBirth = new DateTime(1998, 10, 7),  MarketValue = 70.0,  Goals = 2,  Assists = 10, CleanSheets = 13, TotalPoints = 175 },
                new Player { Id = 31, FirstName = "Andrew",     LastName = "Robertson",       Position = Position.Defender,   Club = "Liverpool", Nationality = "Scotland",    DateOfBirth = new DateTime(1994, 3, 11),  MarketValue = 25.0,  Goals = 1,  Assists = 7,  CleanSheets = 12, TotalPoints = 140 },
                new Player { Id = 32, FirstName = "Ibrahima",   LastName = "Konate",          Position = Position.Defender,   Club = "Liverpool", Nationality = "France",      DateOfBirth = new DateTime(1999, 5, 25),  MarketValue = 55.0,  Goals = 2,  Assists = 0,  CleanSheets = 14, TotalPoints = 148 },
                new Player { Id = 33, FirstName = "Joe",        LastName = "Gomez",           Position = Position.Defender,   Club = "Liverpool", Nationality = "England",     DateOfBirth = new DateTime(1997, 5, 23),  MarketValue = 28.0,  Goals = 0,  Assists = 1,  CleanSheets = 9,  TotalPoints = 98 },
                new Player { Id = 2,  FirstName = "Florian",    LastName = "Wirtz",           Position = Position.Midfielder, Club = "Liverpool", Nationality = "Germany",     DateOfBirth = new DateTime(2003, 5, 3),   MarketValue = 75.0,  Goals = 7,  Assists = 16, CleanSheets = 0,  TotalPoints = 210 },
                new Player { Id = 34, FirstName = "Dominik",    LastName = "Szoboszlai",      Position = Position.Midfielder, Club = "Liverpool", Nationality = "Hungary",     DateOfBirth = new DateTime(2000, 10, 25), MarketValue = 55.0,  Goals = 6,  Assists = 7,  CleanSheets = 0,  TotalPoints = 145 },
                new Player { Id = 35, FirstName = "Alexis",     LastName = "Mac Allister",    Position = Position.Midfielder, Club = "Liverpool", Nationality = "Argentina",   DateOfBirth = new DateTime(1998, 12, 24), MarketValue = 60.0,  Goals = 5,  Assists = 6,  CleanSheets = 0,  TotalPoints = 138 },
                new Player { Id = 36, FirstName = "Ryan",       LastName = "Gravenberch",     Position = Position.Midfielder, Club = "Liverpool", Nationality = "Netherlands", DateOfBirth = new DateTime(2002, 5, 16),  MarketValue = 45.0,  Goals = 3,  Assists = 4,  CleanSheets = 0,  TotalPoints = 122 },
                new Player { Id = 37, FirstName = "Curtis",     LastName = "Jones",           Position = Position.Midfielder, Club = "Liverpool", Nationality = "England",     DateOfBirth = new DateTime(2001, 1, 30),  MarketValue = 30.0,  Goals = 4,  Assists = 3,  CleanSheets = 0,  TotalPoints = 105 },
                new Player { Id = 3,  FirstName = "Mohamed",    LastName = "Salah",           Position = Position.Forward,    Club = "Liverpool", Nationality = "Egypt",       DateOfBirth = new DateTime(1992, 6, 15),  MarketValue = 70.0,  Goals = 19, Assists = 13, CleanSheets = 0,  TotalPoints = 250 },
                new Player { Id = 10, FirstName = "Alexander",  LastName = "Isak",            Position = Position.Forward,    Club = "Liverpool", Nationality = "Sweden",      DateOfBirth = new DateTime(1999, 9, 21),  MarketValue = 95.0,  Goals = 21, Assists = 3,  CleanSheets = 0,  TotalPoints = 230 },
                new Player { Id = 38, FirstName = "Luis",       LastName = "Diaz",            Position = Position.Forward,    Club = "Liverpool", Nationality = "Colombia",    DateOfBirth = new DateTime(1997, 1, 13),  MarketValue = 55.0,  Goals = 10, Assists = 5,  CleanSheets = 0,  TotalPoints = 148 },

                // ==========================================
                // ARSENAL (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 8,  FirstName = "David",    LastName = "Raya",         Position = Position.Goalkeeper, Club = "Arsenal", Nationality = "Spain",    DateOfBirth = new DateTime(1995, 9, 15),  MarketValue = 35.0,  Goals = 0,  Assists = 0,  CleanSheets = 13, TotalPoints = 155 },
                new Player { Id = 39, FirstName = "Karl",     LastName = "Hein",         Position = Position.Goalkeeper, Club = "Arsenal", Nationality = "Estonia",  DateOfBirth = new DateTime(2002, 4, 13),  MarketValue = 5.0,   Goals = 0,  Assists = 0,  CleanSheets = 3,  TotalPoints = 35 },
                new Player { Id = 7,  FirstName = "William",  LastName = "Saliba",       Position = Position.Defender,   Club = "Arsenal", Nationality = "France",   DateOfBirth = new DateTime(2001, 3, 24),  MarketValue = 90.0,  Goals = 2,  Assists = 1,  CleanSheets = 14, TotalPoints = 170 },
                new Player { Id = 40, FirstName = "Gabriel",  LastName = "Magalhaes",    Position = Position.Defender,   Club = "Arsenal", Nationality = "Brazil",   DateOfBirth = new DateTime(1997, 12, 19), MarketValue = 75.0,  Goals = 4,  Assists = 1,  CleanSheets = 13, TotalPoints = 162 },
                new Player { Id = 41, FirstName = "Ben",      LastName = "White",        Position = Position.Defender,   Club = "Arsenal", Nationality = "England",  DateOfBirth = new DateTime(1997, 10, 8),  MarketValue = 50.0,  Goals = 1,  Assists = 5,  CleanSheets = 12, TotalPoints = 142 },
                new Player { Id = 42, FirstName = "Jurrien",  LastName = "Timber",       Position = Position.Defender,   Club = "Arsenal", Nationality = "Netherlands", DateOfBirth = new DateTime(2001, 6, 17), MarketValue = 45.0,  Goals = 1,  Assists = 3,  CleanSheets = 11, TotalPoints = 128 },
                new Player { Id = 43, FirstName = "Riccardo", LastName = "Calafiori",    Position = Position.Defender,   Club = "Arsenal", Nationality = "Italy",    DateOfBirth = new DateTime(2002, 5, 19),  MarketValue = 42.0,  Goals = 1,  Assists = 2,  CleanSheets = 10, TotalPoints = 115 },
                new Player { Id = 6,  FirstName = "Bukayo",   LastName = "Saka",         Position = Position.Midfielder, Club = "Arsenal", Nationality = "England",  DateOfBirth = new DateTime(2001, 9, 5),   MarketValue = 120.0, Goals = 14, Assists = 11, CleanSheets = 0,  TotalPoints = 220 },
                new Player { Id = 44, FirstName = "Martin",   LastName = "Odegaard",     Position = Position.Midfielder, Club = "Arsenal", Nationality = "Norway",   DateOfBirth = new DateTime(1998, 12, 17), MarketValue = 100.0, Goals = 8,  Assists = 12, CleanSheets = 0,  TotalPoints = 195 },
                new Player { Id = 45, FirstName = "Declan",   LastName = "Rice",         Position = Position.Midfielder, Club = "Arsenal", Nationality = "England",  DateOfBirth = new DateTime(1999, 1, 14),  MarketValue = 95.0,  Goals = 5,  Assists = 6,  CleanSheets = 0,  TotalPoints = 158 },
                new Player { Id = 46, FirstName = "Kai",      LastName = "Havertz",      Position = Position.Midfielder, Club = "Arsenal", Nationality = "Germany",  DateOfBirth = new DateTime(1999, 6, 11),  MarketValue = 65.0,  Goals = 11, Assists = 5,  CleanSheets = 0,  TotalPoints = 172 },
                new Player { Id = 47, FirstName = "Thomas",   LastName = "Partey",       Position = Position.Midfielder, Club = "Arsenal", Nationality = "Ghana",    DateOfBirth = new DateTime(1993, 6, 13),  MarketValue = 25.0,  Goals = 2,  Assists = 3,  CleanSheets = 0,  TotalPoints = 95 },
                new Player { Id = 48, FirstName = "Gabriel",  LastName = "Jesus",        Position = Position.Forward,    Club = "Arsenal", Nationality = "Brazil",   DateOfBirth = new DateTime(1997, 4, 3),   MarketValue = 45.0,  Goals = 8,  Assists = 6,  CleanSheets = 0,  TotalPoints = 138 },
                new Player { Id = 49, FirstName = "Leandro",  LastName = "Trossard",     Position = Position.Forward,    Club = "Arsenal", Nationality = "Belgium",  DateOfBirth = new DateTime(1994, 12, 4),  MarketValue = 40.0,  Goals = 10, Assists = 4,  CleanSheets = 0,  TotalPoints = 145 },
                new Player { Id = 50, FirstName = "Eddie",    LastName = "Nketiah",      Position = Position.Forward,    Club = "Arsenal", Nationality = "England",  DateOfBirth = new DateTime(1999, 5, 30),  MarketValue = 28.0,  Goals = 6,  Assists = 2,  CleanSheets = 0,  TotalPoints = 95 },

                // ==========================================
                // CHELSEA (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 51, FirstName = "Robert",   LastName = "Sanchez",      Position = Position.Goalkeeper, Club = "Chelsea", Nationality = "Spain",    DateOfBirth = new DateTime(1997, 11, 18), MarketValue = 22.0,  Goals = 0,  Assists = 0,  CleanSheets = 9,  TotalPoints = 115 },
                new Player { Id = 52, FirstName = "Filip",    LastName = "Jorgensen",    Position = Position.Goalkeeper, Club = "Chelsea", Nationality = "Sweden",   DateOfBirth = new DateTime(2002, 4, 16),  MarketValue = 15.0,  Goals = 0,  Assists = 0,  CleanSheets = 4,  TotalPoints = 52 },
                new Player { Id = 53, FirstName = "Reece",    LastName = "James",        Position = Position.Defender,   Club = "Chelsea", Nationality = "England",  DateOfBirth = new DateTime(1999, 12, 8),  MarketValue = 40.0,  Goals = 1,  Assists = 4,  CleanSheets = 7,  TotalPoints = 108 },
                new Player { Id = 54, FirstName = "Wesley",   LastName = "Fofana",       Position = Position.Defender,   Club = "Chelsea", Nationality = "France",   DateOfBirth = new DateTime(2000, 12, 17), MarketValue = 45.0,  Goals = 1,  Assists = 0,  CleanSheets = 8,  TotalPoints = 105 },
                new Player { Id = 55, FirstName = "Levi",     LastName = "Colwill",      Position = Position.Defender,   Club = "Chelsea", Nationality = "England",  DateOfBirth = new DateTime(2003, 2, 26),  MarketValue = 50.0,  Goals = 2,  Assists = 2,  CleanSheets = 9,  TotalPoints = 125 },
                new Player { Id = 56, FirstName = "Marc",     LastName = "Cucurella",    Position = Position.Defender,   Club = "Chelsea", Nationality = "Spain",    DateOfBirth = new DateTime(1998, 7, 22),  MarketValue = 30.0,  Goals = 1,  Assists = 5,  CleanSheets = 8,  TotalPoints = 118 },
                new Player { Id = 57, FirstName = "Benoit",   LastName = "Badiashile",   Position = Position.Defender,   Club = "Chelsea", Nationality = "France",   DateOfBirth = new DateTime(2001, 3, 26),  MarketValue = 28.0,  Goals = 0,  Assists = 1,  CleanSheets = 7,  TotalPoints = 82 },
                new Player { Id = 9,  FirstName = "Cole",     LastName = "Palmer",       Position = Position.Midfielder, Club = "Chelsea", Nationality = "England",  DateOfBirth = new DateTime(2002, 5, 6),   MarketValue = 110.0, Goals = 22, Assists = 11, CleanSheets = 0,  TotalPoints = 260 },
                new Player { Id = 58, FirstName = "Enzo",     LastName = "Fernandez",    Position = Position.Midfielder, Club = "Chelsea", Nationality = "Argentina", DateOfBirth = new DateTime(2001, 1, 17), MarketValue = 65.0,  Goals = 4,  Assists = 7,  CleanSheets = 0,  TotalPoints = 135 },
                new Player { Id = 59, FirstName = "Moises",   LastName = "Caicedo",      Position = Position.Midfielder, Club = "Chelsea", Nationality = "Ecuador",  DateOfBirth = new DateTime(2001, 11, 2),  MarketValue = 70.0,  Goals = 3,  Assists = 4,  CleanSheets = 0,  TotalPoints = 120 },
                new Player { Id = 60, FirstName = "Romeo",    LastName = "Lavia",        Position = Position.Midfielder, Club = "Chelsea", Nationality = "Belgium",  DateOfBirth = new DateTime(2004, 1, 6),   MarketValue = 45.0,  Goals = 1,  Assists = 3,  CleanSheets = 0,  TotalPoints = 88 },
                new Player { Id = 61, FirstName = "Noni",     LastName = "Madueke",      Position = Position.Midfielder, Club = "Chelsea", Nationality = "England",  DateOfBirth = new DateTime(2002, 3, 10),  MarketValue = 55.0,  Goals = 9,  Assists = 6,  CleanSheets = 0,  TotalPoints = 158 },
                new Player { Id = 62, FirstName = "Nicolas",  LastName = "Jackson",      Position = Position.Forward,    Club = "Chelsea", Nationality = "Senegal",  DateOfBirth = new DateTime(2001, 6, 20),  MarketValue = 50.0,  Goals = 14, Assists = 5,  CleanSheets = 0,  TotalPoints = 168 },
                new Player { Id = 63, FirstName = "Christopher", LastName = "Nkunku",    Position = Position.Forward,    Club = "Chelsea", Nationality = "France",   DateOfBirth = new DateTime(1997, 11, 14), MarketValue = 60.0,  Goals = 11, Assists = 4,  CleanSheets = 0,  TotalPoints = 145 },
                new Player { Id = 64, FirstName = "Mykhailo", LastName = "Mudryk",       Position = Position.Forward,    Club = "Chelsea", Nationality = "Ukraine",  DateOfBirth = new DateTime(2001, 1, 5),   MarketValue = 30.0,  Goals = 5,  Assists = 3,  CleanSheets = 0,  TotalPoints = 88 },

                // ==========================================
                // MANCHESTER UNITED (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 65, FirstName = "Andre",     LastName = "Onana",        Position = Position.Goalkeeper, Club = "Manchester United", Nationality = "Cameroon",    DateOfBirth = new DateTime(1996, 4, 2),   MarketValue = 28.0,  Goals = 0,  Assists = 0,  CleanSheets = 8,  TotalPoints = 108 },
                new Player { Id = 66, FirstName = "Altay",     LastName = "Bayindir",     Position = Position.Goalkeeper, Club = "Manchester United", Nationality = "Turkey",      DateOfBirth = new DateTime(1998, 4, 14),  MarketValue = 8.0,   Goals = 0,  Assists = 0,  CleanSheets = 3,  TotalPoints = 38 },
                new Player { Id = 67, FirstName = "Lisandro",  LastName = "Martinez",     Position = Position.Defender,   Club = "Manchester United", Nationality = "Argentina",   DateOfBirth = new DateTime(1998, 1, 18),  MarketValue = 50.0,  Goals = 2,  Assists = 1,  CleanSheets = 7,  TotalPoints = 115 },
                new Player { Id = 68, FirstName = "Matthijs",  LastName = "de Ligt",      Position = Position.Defender,   Club = "Manchester United", Nationality = "Netherlands", DateOfBirth = new DateTime(1999, 8, 12),  MarketValue = 35.0,  Goals = 1,  Assists = 0,  CleanSheets = 6,  TotalPoints = 92 },
                new Player { Id = 69, FirstName = "Diogo",     LastName = "Dalot",        Position = Position.Defender,   Club = "Manchester United", Nationality = "Portugal",    DateOfBirth = new DateTime(1999, 3, 18),  MarketValue = 38.0,  Goals = 1,  Assists = 4,  CleanSheets = 7,  TotalPoints = 110 },
                new Player { Id = 70, FirstName = "Luke",      LastName = "Shaw",         Position = Position.Defender,   Club = "Manchester United", Nationality = "England",     DateOfBirth = new DateTime(1995, 7, 12),  MarketValue = 20.0,  Goals = 0,  Assists = 3,  CleanSheets = 5,  TotalPoints = 78 },
                new Player { Id = 71, FirstName = "Harry",     LastName = "Maguire",      Position = Position.Defender,   Club = "Manchester United", Nationality = "England",     DateOfBirth = new DateTime(1993, 3, 5),   MarketValue = 15.0,  Goals = 2,  Assists = 0,  CleanSheets = 6,  TotalPoints = 85 },
                new Player { Id = 11, FirstName = "Bruno",     LastName = "Fernandes",    Position = Position.Midfielder, Club = "Manchester United", Nationality = "Portugal",    DateOfBirth = new DateTime(1994, 9, 8),   MarketValue = 60.0,  Goals = 8,  Assists = 8,  CleanSheets = 0,  TotalPoints = 155 },
                new Player { Id = 72, FirstName = "Kobbie",    LastName = "Mainoo",       Position = Position.Midfielder, Club = "Manchester United", Nationality = "England",     DateOfBirth = new DateTime(2005, 4, 19),  MarketValue = 55.0,  Goals = 3,  Assists = 5,  CleanSheets = 0,  TotalPoints = 118 },
                new Player { Id = 73, FirstName = "Mason",     LastName = "Mount",        Position = Position.Midfielder, Club = "Manchester United", Nationality = "England",     DateOfBirth = new DateTime(1999, 1, 10),  MarketValue = 25.0,  Goals = 2,  Assists = 3,  CleanSheets = 0,  TotalPoints = 72 },
                new Player { Id = 74, FirstName = "Amad",      LastName = "Diallo",       Position = Position.Midfielder, Club = "Manchester United", Nationality = "Ivory Coast", DateOfBirth = new DateTime(2002, 7, 11),  MarketValue = 40.0,  Goals = 7,  Assists = 6,  CleanSheets = 0,  TotalPoints = 142 },
                new Player { Id = 75, FirstName = "Alejandro",  LastName = "Garnacho",     Position = Position.Midfielder, Club = "Manchester United", Nationality = "Argentina",      DateOfBirth = new DateTime(1992, 2, 23),  MarketValue = 12.0,  Goals = 1,  Assists = 2,  CleanSheets = 0,  TotalPoints = 65 },
                new Player { Id = 15, FirstName = "Joshua",  LastName = "Zirkzee",        Position = Position.Forward,    Club = "Manchester United", Nationality = "Netherlands",    DateOfBirth = new DateTime(2003, 5, 31),  MarketValue = 50.0,  Goals = 12, Assists = 7,  CleanSheets = 0,  TotalPoints = 175 },
                new Player { Id = 76, FirstName = "Marcus",    LastName = "Rashford",     Position = Position.Forward,    Club = "Manchester United", Nationality = "England",     DateOfBirth = new DateTime(1997, 10, 31), MarketValue = 45.0,  Goals = 7,  Assists = 3,  CleanSheets = 0,  TotalPoints = 105 },
                new Player { Id = 77, FirstName = "Rasmus",    LastName = "Hojlund",      Position = Position.Forward,    Club = "Manchester United", Nationality = "Denmark",     DateOfBirth = new DateTime(2003, 2, 4),   MarketValue = 40.0,  Goals = 10, Assists = 2,  CleanSheets = 0,  TotalPoints = 128 },

                // ==========================================
                // NEWCASTLE (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 12, FirstName = "Nick",      LastName = "Pope",         Position = Position.Goalkeeper, Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(1992, 4, 19),  MarketValue = 20.0,  Goals = 0,  Assists = 0,  CleanSheets = 10, TotalPoints = 130 },
                new Player { Id = 78, FirstName = "Martin",    LastName = "Dubravka",     Position = Position.Goalkeeper, Club = "Newcastle", Nationality = "Slovakia",    DateOfBirth = new DateTime(1989, 1, 15),  MarketValue = 5.0,   Goals = 0,  Assists = 0,  CleanSheets = 3,  TotalPoints = 35 },
                new Player { Id = 79, FirstName = "Kieran",    LastName = "Trippier",     Position = Position.Defender,   Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(1990, 9, 19),  MarketValue = 15.0,  Goals = 1,  Assists = 6,  CleanSheets = 8,  TotalPoints = 118 },
                new Player { Id = 80, FirstName = "Sven",      LastName = "Botman",       Position = Position.Defender,   Club = "Newcastle", Nationality = "Netherlands", DateOfBirth = new DateTime(2000, 1, 12),  MarketValue = 45.0,  Goals = 1,  Assists = 0,  CleanSheets = 9,  TotalPoints = 112 },
                new Player { Id = 81, FirstName = "Dan",       LastName = "Burn",         Position = Position.Defender,   Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(1992, 5, 9),   MarketValue = 12.0,  Goals = 2,  Assists = 1,  CleanSheets = 8,  TotalPoints = 105 },
                new Player { Id = 82, FirstName = "Fabian",    LastName = "Schar",        Position = Position.Defender,   Club = "Newcastle", Nationality = "Switzerland", DateOfBirth = new DateTime(1991, 12, 20), MarketValue = 10.0,  Goals = 1,  Assists = 0,  CleanSheets = 7,  TotalPoints = 88 },
                new Player { Id = 83, FirstName = "Lewis",     LastName = "Hall",         Position = Position.Defender,   Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(2004, 9, 8),   MarketValue = 25.0,  Goals = 0,  Assists = 4,  CleanSheets = 7,  TotalPoints = 95 },
                new Player { Id = 84, FirstName = "Bruno",     LastName = "Guimaraes",    Position = Position.Midfielder, Club = "Newcastle", Nationality = "Brazil",      DateOfBirth = new DateTime(1997, 11, 16), MarketValue = 80.0,  Goals = 6,  Assists = 7,  CleanSheets = 0,  TotalPoints = 155 },
                new Player { Id = 85, FirstName = "Joelinton", LastName = "Cassio",       Position = Position.Midfielder, Club = "Newcastle", Nationality = "Brazil",      DateOfBirth = new DateTime(1996, 8, 14),  MarketValue = 35.0,  Goals = 4,  Assists = 3,  CleanSheets = 0,  TotalPoints = 108 },
                new Player { Id = 86, FirstName = "Anthony",   LastName = "Gordon",       Position = Position.Midfielder, Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(2001, 2, 24),  MarketValue = 60.0,  Goals = 10, Assists = 6,  CleanSheets = 0,  TotalPoints = 168 },
                new Player { Id = 87, FirstName = "Sean",      LastName = "Longstaff",    Position = Position.Midfielder, Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(1997, 10, 30), MarketValue = 18.0,  Goals = 2,  Assists = 3,  CleanSheets = 0,  TotalPoints = 78 },
                new Player { Id = 88, FirstName = "Joe",       LastName = "Willock",      Position = Position.Midfielder, Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(1999, 8, 20),  MarketValue = 20.0,  Goals = 3,  Assists = 2,  CleanSheets = 0,  TotalPoints = 82 },
                new Player { Id = 89, FirstName = "Callum",    LastName = "Wilson",       Position = Position.Forward,    Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(1992, 2, 27),  MarketValue = 15.0,  Goals = 7,  Assists = 3,  CleanSheets = 0,  TotalPoints = 108 },
                new Player { Id = 90, FirstName = "Harvey",    LastName = "Barnes",       Position = Position.Forward,    Club = "Newcastle", Nationality = "England",     DateOfBirth = new DateTime(1997, 12, 9),  MarketValue = 30.0,  Goals = 8,  Assists = 5,  CleanSheets = 0,  TotalPoints = 128 },
                new Player { Id = 91, FirstName = "Miguel",    LastName = "Almiron",      Position = Position.Forward,    Club = "Newcastle", Nationality = "Paraguay",    DateOfBirth = new DateTime(1994, 2, 10),  MarketValue = 18.0,  Goals = 5,  Assists = 4,  CleanSheets = 0,  TotalPoints = 92 },

                // ==========================================
                // ASTON VILLA (2 GK, 5 DEF, 5 MID, 3 FWD)
                // ==========================================
                new Player { Id = 92,  FirstName = "Emiliano",  LastName = "Martinez",     Position = Position.Goalkeeper, Club = "Aston Villa", Nationality = "Argentina",   DateOfBirth = new DateTime(1992, 9, 2),   MarketValue = 35.0,  Goals = 0,  Assists = 0,  CleanSheets = 12, TotalPoints = 148 },
                new Player { Id = 93,  FirstName = "Robin",     LastName = "Olsen",        Position = Position.Goalkeeper, Club = "Aston Villa", Nationality = "Sweden",      DateOfBirth = new DateTime(1990, 1, 8),   MarketValue = 3.0,   Goals = 0,  Assists = 0,  CleanSheets = 2,  TotalPoints = 28 },
                new Player { Id = 94,  FirstName = "Ezri",      LastName = "Konsa",        Position = Position.Defender,   Club = "Aston Villa", Nationality = "England",     DateOfBirth = new DateTime(1997, 10, 23), MarketValue = 40.0,  Goals = 2,  Assists = 1,  CleanSheets = 10, TotalPoints = 128 },
                new Player { Id = 95,  FirstName = "Pau",       LastName = "Torres",       Position = Position.Defender,   Club = "Aston Villa", Nationality = "Spain",       DateOfBirth = new DateTime(1997, 1, 16),  MarketValue = 42.0,  Goals = 1,  Assists = 2,  CleanSheets = 10, TotalPoints = 122 },
                new Player { Id = 96,  FirstName = "Lucas",     LastName = "Digne",        Position = Position.Defender,   Club = "Aston Villa", Nationality = "France",      DateOfBirth = new DateTime(1993, 7, 20),  MarketValue = 15.0,  Goals = 1,  Assists = 5,  CleanSheets = 8,  TotalPoints = 110 },
                new Player { Id = 97,  FirstName = "Matty",     LastName = "Cash",         Position = Position.Defender,   Club = "Aston Villa", Nationality = "Poland",      DateOfBirth = new DateTime(1997, 8, 7),   MarketValue = 22.0,  Goals = 1,  Assists = 4,  CleanSheets = 8,  TotalPoints = 105 },
                new Player { Id = 98,  FirstName = "Tyrone",    LastName = "Mings",        Position = Position.Defender,   Club = "Aston Villa", Nationality = "England",     DateOfBirth = new DateTime(1993, 3, 13),  MarketValue = 12.0,  Goals = 1,  Assists = 0,  CleanSheets = 7,  TotalPoints = 82 },
                new Player { Id = 99,  FirstName = "John",      LastName = "McGinn",       Position = Position.Midfielder, Club = "Aston Villa", Nationality = "Scotland",    DateOfBirth = new DateTime(1994, 10, 18), MarketValue = 38.0,  Goals = 6,  Assists = 5,  CleanSheets = 0,  TotalPoints = 138 },
                new Player { Id = 100, FirstName = "Youri",     LastName = "Tielemans",    Position = Position.Midfielder, Club = "Aston Villa", Nationality = "Belgium",     DateOfBirth = new DateTime(1997, 5, 7),   MarketValue = 30.0,  Goals = 4,  Assists = 6,  CleanSheets = 0,  TotalPoints = 125 },
                new Player { Id = 101, FirstName = "Morgan",    LastName = "Rogers",       Position = Position.Midfielder, Club = "Aston Villa", Nationality = "England",     DateOfBirth = new DateTime(2002, 7, 26),  MarketValue = 35.0,  Goals = 8,  Assists = 5,  CleanSheets = 0,  TotalPoints = 148 },
                new Player { Id = 102, FirstName = "Leon",      LastName = "Bailey",       Position = Position.Midfielder, Club = "Aston Villa", Nationality = "Jamaica",     DateOfBirth = new DateTime(1997, 8, 9),   MarketValue = 28.0,  Goals = 7,  Assists = 4,  CleanSheets = 0,  TotalPoints = 128 },
                new Player { Id = 103, FirstName = "Jacob",     LastName = "Ramsey",       Position = Position.Midfielder, Club = "Aston Villa", Nationality = "England",     DateOfBirth = new DateTime(2001, 5, 28),  MarketValue = 25.0,  Goals = 3,  Assists = 3,  CleanSheets = 0,  TotalPoints = 88 },
                new Player { Id = 14, FirstName = "Ollie",      LastName = "Watkins",      Position = Position.Forward,    Club = "Aston Villa", Nationality = "England",     DateOfBirth = new DateTime(1995, 12, 30), MarketValue = 65.0,  Goals = 15, Assists = 9,  CleanSheets = 0,  TotalPoints = 195 },
                new Player { Id = 104, FirstName = "Jhon",      LastName = "Duran",        Position = Position.Forward,    Club = "Aston Villa", Nationality = "Colombia",    DateOfBirth = new DateTime(2003, 12, 13), MarketValue = 35.0,  Goals = 10, Assists = 2,  CleanSheets = 0,  TotalPoints = 128 },
                new Player { Id = 105, FirstName = "Moussa",    LastName = "Diaby",        Position = Position.Forward,    Club = "Aston Villa", Nationality = "France",      DateOfBirth = new DateTime(1999, 7, 7),   MarketValue = 42.0,  Goals = 7,  Assists = 6,  CleanSheets = 0,  TotalPoints = 118 },
            };
        }

        public List<Player> GetAll() => _players;
        public Player? GetById(int id) => _players.FirstOrDefault(p => p.Id == id);
    }
}
